import json
import requests

with open('/Users/farvascott/.openclaw/workspace/.secrets/facebook-credentials.json', 'r') as f:
    creds = json.load(f)

page_token = next(page['access_token'] for page in creds['pages'] if page['name'] == 'The Ethics Reporter')
page_id = next(page['id'] for page in creds['pages'] if page['name'] == 'The Ethics Reporter')

message = "NEW OPINION: The Elite Hallucination.\n\nOn April 21, 2026, elite white-shoe law firm Sullivan & Cromwell was forced to apologize for submitting a court document containing fake citations generated by AI.\n\nThis completely shatters the legal establishment's favorite myth: that AI mistakes are only a danger to \"sloppy\" solo practitioners. The elite firewall failed, proving that the cartel's draconian sanctions and ethics rules are not about protecting the judicial record—they are about protecting the billable hour from technological obsolescence.\n\nRead the full commentary and analysis on The Ethics Reporter:"
link = "https://theethicsreporter.com/2026/04/27/sullivan-cromwell-ai-hallucination-elite-cartel-myth-2026/"

url = f"https://graph.facebook.com/v19.0/{page_id}/feed"
payload = {
    'message': message,
    'link': link,
    'access_token': page_token
}

response = requests.post(url, data=payload)
print(response.json())
