import json
import subprocess
from datetime import datetime, timezone
import os
import sys

json_path = '/Users/farvascott/code/theethicsreporter/site/data/posts.json'
with open(json_path, 'r') as f:
    posts = json.load(f)

slug = f'ai-gatekeeping-courts-cartel-preservation-{datetime.now(timezone.utc).strftime("%Y%m%d%H%M")}'
title = 'The Disciplinary Cartel: How Courts Weaponize Ethics to Protect the Legal Monopoly from AI'
now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S')

content = """<div style="background:#f4f4f4;border-left:4px solid #c0392b;padding:16px 20px;margin-bottom:28px;">
<strong>&#9889; QUICK FACTS</strong>
<ul>
<li><strong>The Double Standard:</strong> While human associates constantly submit poor or outdated case law with minor consequences, generative AI errors are met with career-destroying public sanctions and sweeping standing orders.</li>
<li><strong>The Real Threat:</strong> Generative AI in 2026 is rapidly making the traditional billable hour obsolete, threatening the core economic engine of the legal establishment.</li>
<li><strong>Weaponized Ethics:</strong> Bar associations and courts are interpreting "unauthorized practice of law" (UPL) and Rule 11 to implicitly target the *use of technology* rather than the actual harm to clients.</li>
<li><strong>The Outcome:</strong> By artificially inflating the risk of AI use, the legal cartel forces clients to continue paying exorbitant fees for work that software can now perform in seconds.</li>
</ul>
</div>

<p>The American legal profession is currently engaged in the most aggressive campaign of institutional self-preservation since the early 20th century, and it is doing so under the guise of "legal ethics." Across the country, federal and state courts are issuing sweeping standing orders, bar associations are convening emergency task forces, and disciplinary committees are salivating over the chance to sanction any attorney caught using generative artificial intelligence.</p>

<p>We are told this is a necessary defense of the rule of law. We are told that AI "hallucinations" pose an existential threat to the integrity of the judicial process. We are told that the public must be protected from algorithmic malpractice. Do not believe a word of it. This is not about protecting the public. This is about protecting a cartel. It is about a monopoly recognizing that its core commodity—access to legal knowledge—is being radically democratized, and weaponizing its regulatory power to crush the competition.</p>

<h2 style="color:#8B0000; font-family:Georgia,serif; margin-top:32px;">The Hypocrisy of the "Hallucination" Panic</h2>

<p>To understand the sheer cynicism of the legal establishment’s response to AI, one only has to look at how human error is treated in the courtroom. For centuries, lawyers have submitted briefs containing overturned precedent, mischaracterized holdings, and flat-out wrong citations. The standard remedy for this is straightforward: opposing counsel points it out, the judge ignores the bad citation, and the offending lawyer looks foolish. Sometimes, if the error is particularly egregious and intentional, there might be a Rule 11 sanction. But generally, human incompetence is treated as a routine friction cost of the adversarial system.</p>

<p>Contrast this with the hysteria surrounding the 2023 <em>Mata v. Avianca</em> case, where two New York attorneys submitted a brief generated by ChatGPT containing fabricated citations. The attorneys were rightfully sanctioned. But the reaction from the broader legal community was entirely disproportionate to the actual harm. The case became international news. It spawned endless symposia, panicked law review articles, and a wave of judicial standing orders demanding that attorneys affirmatively certify they did not use AI, or if they did, that every word was human-verified under penalty of perjury.</p>

<p>Why the discrepancy? Why is a human failing to properly Shepardize a case a minor annoyance, while a machine making the exact same error an existential crisis? Because the machine is cheap. The human error was produced by an associate billing $400 an hour. The machine error was produced by a $20-a-month subscription. The legal establishment can tolerate incompetence, provided it is properly credentialed and expensively billed. What it cannot tolerate is efficiency.</p>

<p>By amplifying every AI hallucination into a moral panic, the courts are creating an artificial risk premium. They are sending a clear message to practitioners: if you use this technology and make a mistake, we will not just correct you; we will destroy your reputation and suspend your license. This chilling effect is exactly the goal. It keeps lawyers terrified of adopting efficiency-enhancing tools, ensuring they continue to bill clients for the manual, grueling labor that sustains law firm partnerships.</p>

<h2 style="color:#8B0000; font-family:Georgia,serif; margin-top:32px;">The Economics of Artificial Scarcity</h2>

<p>To fully grasp the stakes, we must look at the economic structure of the modern law firm. The traditional "Cravath system" relies on a pyramid structure: partners at the top leverage the labor of an army of associates at the bottom. These associates spend their days engaged in document review, legal research, and drafting basic memoranda—tasks that are highly repetitive, deeply tedious, and massively profitable.</p>

<p>Generative AI, particularly the large language models of 2026, can perform a vast majority of these tasks with greater speed and accuracy than a sleep-deprived 25-year-old. When a sophisticated AI model can ingest a 10,000-page discovery cache and synthesize the key communications in three minutes, the economic justification for the associate army evaporates. The pyramid collapses.</p>

<p>The legal profession understands this math perfectly. But instead of adapting—instead of passing the massive cost savings on to clients and focusing on higher-level strategic judgment—the profession has opted for regulatory capture. By leveraging their dual role as market participants and market regulators, lawyers are using the rules of professional conduct to ban the tools of their own disruption.</p>

<p>Consider the concept of the "Unauthorized Practice of Law" (UPL). Historically, UPL statutes were designed to prevent charlatans from defrauding vulnerable people in court. Today, state bar associations are aggressively expanding the definition of UPL to encompass software platforms. If a generative AI model drafts a legally sound contract for a small business owner for $5, the bar association views it not as a triumph of access to justice, but as a criminal offense.</p>

<p>This is protectionism in its purest form. It is the modern equivalent of taxi medallions trying to ban ridesharing, or the weavers’ guilds smashing the power looms. The difference is that the legal profession writes the laws, staffs the courts, and disciplines the competitors.</p>

<h2 style="color:#8B0000; font-family:Georgia,serif; margin-top:32px;">The Standing Orders: A Performance of Authority</h2>

<p>The most visible manifestation of this protectionism is the proliferation of judicial standing orders regarding AI. Across federal districts, judges have enacted rules requiring lawyers to disclose any use of generative AI in their filings. Some judges require a separate certification; others demand to know exactly which portions of the document were AI-generated and which were human-drafted.</p>

<p>These orders are performative nonsense. They are completely unenforceable. How, exactly, does a judge intend to prove that a paragraph summarizing a line of tort cases was written by Claude 3.5 instead of a junior associate? They cannot. And what is the functional difference between an attorney using AI to synthesize research and an attorney using an associate to do the same? In both cases, the attorney of record is ultimately responsible for the final product. Rule 11 of the Federal Rules of Civil Procedure already requires attorneys to certify that their submissions are legally and factually sound. Adding a specific "No AI" clause does nothing to enhance the accuracy of the briefing; it only serves to stigmatize the technology.</p>

<p>Furthermore, these standing orders betray a profound ignorance of how legal technology actually works. AI is no longer a separate, discrete tool that one explicitly chooses to use; it is deeply integrated into the very fabric of legal software. Westlaw, LexisNexis, and Microsoft Word all incorporate generative AI into their core functionalities. By demanding that lawyers disclose "any use" of AI, judges are demanding the impossible. They are trying to legislate the tide.</p>

<h2 style="color:#8B0000; font-family:Georgia,serif; margin-top:32px;">The Cost to the Public</h2>

<p>The victims in this regulatory war are not the AI companies, who will survive just fine. The victims are the American people. We have a legal system that is fundamentally broken due to cost. The vast majority of Americans cannot afford a lawyer for basic civil disputes. Family law, housing court, and consumer debt dockets are choked with pro se litigants who are utterly unequipped to navigate the procedural labyrinth.</p>

<p>Generative AI offers a generational opportunity to close the access to justice gap. For the first time in history, we have the technological capability to provide competent, cheap legal guidance to anyone with a smartphone. We could automate the drafting of routine pleadings, simplify the discovery process, and make the law comprehensible to the people it governs.</p>

<p>But the legal establishment will not allow it. By weaponizing ethics rules, aggressively enforcing UPL statutes, and issuing draconian standing orders, the profession is artificially keeping the cost of legal services high. They are denying justice to millions of people in order to protect the profit margins of a few.</p>

<h2 style="color:#8B0000; font-family:Georgia,serif; margin-top:32px;">The Future of the Cartel</h2>

<p>History strongly suggests that protectionist cartels cannot survive technological revolutions forever. The economic incentives are simply too powerful. Eventually, clients—particularly massive corporate clients who pay the BigLaw bills—will refuse to subsidize the associate pyramid. They will demand the efficiency that AI provides, and the firms that refuse to adapt will die.</p>

<p>But in the short term, the profession will continue to fight dirty. We will see more high-profile sanctions. We will see more bar association task forces producing thousands of pages of report warning of the "dangers" of algorithmic bias, while conveniently ignoring the massive, systemic biases of human judges and juries. We will hear endless pious speeches about the sacred duty of the lawyer and the irreplaceable nature of human judgment.</p>

<p>When you hear these arguments, recognize them for what they are: the death rattle of a monopoly. The legal profession is not trying to protect the public from artificial intelligence. It is desperately trying to protect itself from the future. And it is using the disciplinary system as a weapon, proving once and for all that in the legal world, "ethics" is just another word for leverage.</p>

<p>The facade is crumbling. The profession cannot gatekeep knowledge forever. The technology is simply too good, and the current system is simply too expensive. The cartel may win a few highly publicized skirmishes in the disciplinary courts, but they have already lost the war.</p>
"""

excerpt = '<p>The legal profession is currently engaged in the most aggressive campaign of institutional self-preservation since the early 20th century, using the guise of "legal ethics" to weaponize sanctions and crush the AI technology that threatens their billable hours and monopoly pricing power.</p>'

new_id = max((post.get('id', 0) for post in posts), default=0) + 1

new_post = {
    'id': new_id,
    'title': title,
    'slug': slug,
    'date': now,
    'modified': now,
    'content': content,
    'excerpt': excerpt,
    'link': f'https://theethicsreporter.com/{now[:4]}/{now[5:7]}/{now[8:10]}/{slug}/',
    'status': 'publish',
    'featured_image': f'/images/posts/{slug}.jpg',
    'categories': [1, 2],
    'tags': ['AI', 'Legal Ethics', 'Gatekeeping', 'Monopoly', 'Sanctions']
}

posts.insert(0, new_post)

with open(json_path, 'w') as f:
    json.dump(posts, f, indent=2)

print(f"Added post {new_id} - {title}")

# Optional: also run the push and deploy if required, we will do it sequentially in bash
