export interface CityData {
  slug: string;
  name: string;
  state: string;
  stateSlug: string;
  barBody: string;
  barUrl: string;
  description: string;
  keywords: string[];
}

export const citiesData: CityData[] = [
  // New York City boroughs and areas
  {
    slug: "new-york-city",
    name: "New York City",
    state: "New York",
    stateSlug: "new-york",
    barBody: "First & Second Department Grievance Committees (NYSBA)",
    barUrl: "https://iapps.courts.state.ny.us/attorney/AttorneySearch",
    description: "New York City is home to the largest concentration of attorneys in the United States, and its attorney discipline system is divided between the First Department (Manhattan and the Bronx) and the Second Department (Brooklyn, Queens, and Staten Island). The Ethics Reporter covers attorney misconduct across all five boroughs, from complex commercial litigation fraud to immigration attorney misconduct preying on vulnerable clients.",
    keywords: ["New York City attorney misconduct", "NYC attorney ethics", "New York attorney discipline", "NYC bar complaint", "New York lawyer investigation"],
  },
  {
    slug: "manhattan",
    name: "Manhattan",
    state: "New York",
    stateSlug: "new-york",
    barBody: "First Department Departmental Disciplinary Committee (DDC)",
    barUrl: "https://www.nycourts.gov/courts/ad1/committees&programs/ddc/index.shtml",
    description: "Manhattan is the legal capital of New York State, home to thousands of attorneys practicing in every area of law. Attorney discipline for Manhattan lawyers falls under the First Department Departmental Disciplinary Committee. The Ethics Reporter covers attorney misconduct investigations involving Manhattan attorneys, including the investigation of EPRA Legal's Ernestas Pravilionis, who lists a Manhattan virtual mailbox as his primary office.",
    keywords: ["Manhattan attorney ethics", "Manhattan lawyer misconduct", "First Department DDC", "Manhattan attorney discipline", "New York attorney investigation Manhattan"],
  },
  {
    slug: "brooklyn",
    name: "Brooklyn",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Second Judicial Department",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Brooklyn, New York's most populous borough, has a large and diverse legal community serving one of the most densely populated urban areas in the United States. Attorney discipline for Brooklyn lawyers falls under the Second Department Attorney Grievance Committee. The Ethics Reporter investigates attorney misconduct in Brooklyn with attention to cases affecting the borough's many immigrant and low-income communities.",
    keywords: ["Brooklyn attorney ethics", "Brooklyn lawyer misconduct", "Second Department grievance committee Brooklyn", "Brooklyn attorney discipline", "Brooklyn attorney investigation"],
  },
  {
    slug: "queens",
    name: "Queens",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Second Judicial Department",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Queens is one of the most ethnically diverse counties in the United States, and its legal community serves a large immigrant population particularly vulnerable to attorney misconduct in immigration matters. Attorney discipline for Queens attorneys falls under the Second Department Attorney Grievance Committee. The Ethics Reporter investigates immigration attorney fraud and other misconduct affecting Queens residents.",
    keywords: ["Queens attorney ethics", "Queens lawyer misconduct", "Queens attorney discipline", "Queens immigration attorney fraud", "Queens attorney investigation"],
  },
  {
    slug: "the-bronx",
    name: "The Bronx",
    state: "New York",
    stateSlug: "new-york",
    barBody: "First Department Departmental Disciplinary Committee (DDC)",
    barUrl: "https://www.nycourts.gov/courts/ad1/committees&programs/ddc/index.shtml",
    description: "The Bronx's legal community serves one of New York City's most economically challenged boroughs. Attorney discipline for Bronx attorneys falls under the First Department Departmental Disciplinary Committee. The Ethics Reporter covers attorney misconduct affecting Bronx residents, including criminal defense failures and client fund misappropriation cases.",
    keywords: ["Bronx attorney ethics", "Bronx lawyer misconduct", "Bronx attorney discipline", "First Department DDC Bronx", "Bronx attorney investigation"],
  },
  {
    slug: "staten-island",
    name: "Staten Island",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Second Judicial Department",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Staten Island's legal community serves the borough's mix of residential and commercial interests. Attorney discipline for Staten Island attorneys falls under the Second Department Attorney Grievance Committee. The Ethics Reporter covers attorney misconduct investigations on Staten Island, with particular attention to real estate and estate planning violations.",
    keywords: ["Staten Island attorney ethics", "Staten Island lawyer misconduct", "Staten Island attorney discipline", "Second Department grievance Staten Island", "Staten Island attorney investigation"],
  },
  // Upstate New York
  {
    slug: "buffalo",
    name: "Buffalo",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Fourth Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad4/index.shtml",
    description: "Buffalo is the second-largest city in New York State and the center of legal practice in Western New York. Attorney discipline for Buffalo attorneys falls under the Fourth Department Attorney Grievance Committee. The Ethics Reporter covers attorney misconduct in the Buffalo region, including cases involving personal injury fraud, client fund theft, and criminal defense failures.",
    keywords: ["Buffalo attorney ethics", "Buffalo lawyer misconduct", "Fourth Department grievance Buffalo", "Buffalo attorney discipline", "Western New York attorney investigation"],
  },
  {
    slug: "rochester",
    name: "Rochester",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Fourth Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad4/index.shtml",
    description: "Rochester, in Monroe County, is a major legal market in upstate New York. Attorney discipline for Rochester attorneys falls under the Fourth Department Attorney Grievance Committee. The Ethics Reporter covers attorney misconduct across the Rochester area.",
    keywords: ["Rochester attorney ethics", "Rochester lawyer misconduct", "Fourth Department grievance Rochester", "Rochester attorney discipline", "Monroe County attorney investigation"],
  },
  {
    slug: "syracuse",
    name: "Syracuse",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Fourth Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad4/index.shtml",
    description: "Syracuse, the seat of Onondaga County, is a central hub for legal practice in Central New York. Attorney discipline for Syracuse attorneys falls under the Fourth Department Attorney Grievance Committee.",
    keywords: ["Syracuse attorney ethics", "Syracuse lawyer misconduct", "Syracuse attorney discipline", "Onondaga County attorney investigation", "Central New York attorney ethics"],
  },
  {
    slug: "albany",
    name: "Albany",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Third Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad3/index.shtml",
    description: "Albany, the capital of New York State, has a large legal community concentrated around state government, the appellate courts, and regulatory practice. Attorney discipline for Albany attorneys falls under the Third Department Attorney Grievance Committee. The Ethics Reporter notes that EPRA Legal's Ernestas Pravilionis lists an Albany virtual mailbox as an office address.",
    keywords: ["Albany attorney ethics", "Albany lawyer misconduct", "Third Department grievance Albany", "Albany attorney discipline", "Capital District attorney investigation"],
  },
  {
    slug: "yonkers",
    name: "Yonkers",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Yonkers, in Westchester County, is the fourth-largest city in New York State. Attorney discipline for Yonkers attorneys falls under the Second Department. The Ethics Reporter covers attorney misconduct in Westchester County including Yonkers.",
    keywords: ["Yonkers attorney ethics", "Yonkers lawyer misconduct", "Westchester attorney discipline", "Yonkers attorney investigation", "Second Department Westchester"],
  },
  {
    slug: "white-plains",
    name: "White Plains",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "White Plains is the county seat of Westchester County and a major legal center, home to the Westchester County Courthouse and numerous law firms serving the region. Attorney discipline for White Plains attorneys falls under the Second Department.",
    keywords: ["White Plains attorney ethics", "Westchester County attorney misconduct", "White Plains lawyer discipline", "White Plains attorney investigation", "Westchester bar complaint"],
  },
  {
    slug: "newburgh",
    name: "Newburgh",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Newburgh, in Orange County, is part of the Hudson Valley legal market overseen by the Second Department Attorney Grievance Committee.",
    keywords: ["Newburgh attorney ethics", "Orange County attorney misconduct", "Newburgh lawyer discipline", "Hudson Valley attorney investigation", "Orange County bar complaint"],
  },
  {
    slug: "poughkeepsie",
    name: "Poughkeepsie",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Poughkeepsie is the seat of Dutchess County in the Hudson Valley. The Ethics Reporter notes that EPRA Legal's Ernestas Pravilionis lists a Poughkeepsie coworking space (Barnfox) as an office address, which appears to be a flexible workspace rather than a permanent law office. Attorney discipline for Poughkeepsie attorneys falls under the Second Department.",
    keywords: ["Poughkeepsie attorney ethics", "Dutchess County attorney misconduct", "Poughkeepsie lawyer discipline", "Hudson Valley attorney investigation", "Dutchess County bar complaint"],
  },
  {
    slug: "kingston",
    name: "Kingston",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Third Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad3/index.shtml",
    description: "Kingston, the seat of Ulster County, is served by the Third Department Attorney Grievance Committee for attorney discipline matters.",
    keywords: ["Kingston attorney ethics", "Ulster County attorney misconduct", "Kingston lawyer discipline", "Ulster County attorney investigation", "Hudson Valley bar complaint"],
  },
  {
    slug: "new-rochelle",
    name: "New Rochelle",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "New Rochelle, in Westchester County, is part of the greater New York metropolitan legal market and subject to Second Department disciplinary oversight.",
    keywords: ["New Rochelle attorney ethics", "Westchester attorney misconduct", "New Rochelle lawyer discipline", "New Rochelle attorney investigation", "Westchester County bar complaint"],
  },
  {
    slug: "mount-vernon",
    name: "Mount Vernon",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Mount Vernon, in Westchester County, is served by the Second Department for attorney discipline matters.",
    keywords: ["Mount Vernon attorney ethics", "Mount Vernon lawyer misconduct", "Westchester attorney discipline", "Mount Vernon attorney investigation", "Second Department Westchester"],
  },
  {
    slug: "schenectady",
    name: "Schenectady",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Third Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad3/index.shtml",
    description: "Schenectady, in the Capital District, is served by the Third Department Attorney Grievance Committee for attorney discipline matters.",
    keywords: ["Schenectady attorney ethics", "Schenectady lawyer misconduct", "Third Department grievance Schenectady", "Schenectady attorney investigation", "Capital District attorney ethics"],
  },
  {
    slug: "utica",
    name: "Utica",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Fourth Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad4/index.shtml",
    description: "Utica, in Oneida County, is served by the Fourth Department Attorney Grievance Committee for attorney discipline matters.",
    keywords: ["Utica attorney ethics", "Utica lawyer misconduct", "Fourth Department Utica", "Oneida County attorney investigation", "Utica attorney discipline"],
  },
  {
    slug: "troy",
    name: "Troy",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Third Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad3/index.shtml",
    description: "Troy, the seat of Rensselaer County in the Capital District, is served by the Third Department Attorney Grievance Committee for attorney discipline matters.",
    keywords: ["Troy attorney ethics", "Troy lawyer misconduct", "Third Department Troy", "Rensselaer County attorney investigation", "Capital District attorney discipline"],
  },
  {
    slug: "niagara-falls",
    name: "Niagara Falls",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Fourth Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad4/index.shtml",
    description: "Niagara Falls, in Niagara County in Western New York, is served by the Fourth Department Attorney Grievance Committee for attorney discipline matters.",
    keywords: ["Niagara Falls attorney ethics", "Niagara County attorney misconduct", "Niagara Falls lawyer discipline", "Western New York attorney investigation", "Fourth Department attorney discipline"],
  },
  {
    slug: "binghamton",
    name: "Binghamton",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Third Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad3/index.shtml",
    description: "Binghamton, the seat of Broome County, is the main legal hub in the Southern Tier of New York. Attorney discipline falls under the Third Department Attorney Grievance Committee.",
    keywords: ["Binghamton attorney ethics", "Broome County attorney misconduct", "Binghamton lawyer discipline", "Southern Tier attorney investigation", "Third Department attorney discipline"],
  },
  {
    slug: "long-island",
    name: "Long Island",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Tenth Judicial District (Nassau/Suffolk)",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Long Island — comprising Nassau and Suffolk counties — is one of the largest suburban legal markets in the country. Attorney discipline for Long Island attorneys falls under the Second Department, with local committees covering the Tenth Judicial District. The Ethics Reporter investigates attorney misconduct across Long Island including real estate fraud, personal injury manipulation, and estate planning violations.",
    keywords: ["Long Island attorney ethics", "Long Island lawyer misconduct", "Nassau County attorney discipline", "Suffolk County attorney discipline", "Long Island attorney investigation"],
  },
  {
    slug: "nassau-county",
    name: "Nassau County",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Tenth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Nassau County is one of the most densely populated suburban counties in the United States and has a large legal community. Attorney discipline falls under the Second Department Attorney Grievance Committee's Tenth Judicial District.",
    keywords: ["Nassau County attorney ethics", "Nassau County lawyer misconduct", "Nassau County attorney discipline", "Nassau County attorney investigation", "Long Island attorney ethics Nassau"],
  },
  {
    slug: "suffolk-county",
    name: "Suffolk County",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Tenth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Suffolk County is the easternmost county on Long Island and has a large and active legal community. Attorney discipline falls under the Second Department Attorney Grievance Committee's Tenth Judicial District.",
    keywords: ["Suffolk County attorney ethics", "Suffolk County lawyer misconduct", "Suffolk County attorney discipline", "Suffolk County attorney investigation", "Long Island attorney ethics Suffolk"],
  },
  {
    slug: "westchester-county",
    name: "Westchester County",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Westchester County, directly north of New York City, is a large suburban legal market with significant commercial, real estate, and family law practices. Attorney discipline falls under the Second Department's Ninth Judicial District committee.",
    keywords: ["Westchester County attorney ethics", "Westchester lawyer misconduct", "Westchester attorney discipline", "Westchester attorney investigation", "Ninth Judicial District attorney ethics"],
  },
  {
    slug: "rockland-county",
    name: "Rockland County",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Rockland County, west of the Hudson River, is served by the Second Department's Ninth Judicial District committee for attorney discipline.",
    keywords: ["Rockland County attorney ethics", "Rockland County lawyer misconduct", "Rockland County attorney discipline", "Rockland County attorney investigation", "Second Department attorney ethics Rockland"],
  },
  {
    slug: "orange-county-ny",
    name: "Orange County",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Orange County, in the Hudson Valley, is served by the Second Department's Ninth Judicial District committee for attorney discipline. The county's growing population has increased demand for legal services and, unfortunately, the potential for attorney misconduct.",
    keywords: ["Orange County NY attorney ethics", "Orange County New York lawyer misconduct", "Orange County attorney discipline", "Hudson Valley attorney investigation", "Orange County NY bar complaint"],
  },
  {
    slug: "dutchess-county",
    name: "Dutchess County",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Dutchess County, in the Mid-Hudson Valley, is served by the Second Department's Ninth Judicial District committee. The Ethics Reporter notes the Poughkeepsie connection to the Ernestas Pravilionis investigation.",
    keywords: ["Dutchess County attorney ethics", "Dutchess County lawyer misconduct", "Dutchess County attorney discipline", "Mid-Hudson Valley attorney investigation", "Poughkeepsie attorney bar complaint"],
  },
  {
    slug: "ulster-county",
    name: "Ulster County",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Third Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad3/index.shtml",
    description: "Ulster County, in the Hudson Valley, is served by the Third Department Attorney Grievance Committee for attorney discipline matters.",
    keywords: ["Ulster County attorney ethics", "Ulster County lawyer misconduct", "Ulster County attorney discipline", "Hudson Valley attorney investigation", "Kingston attorney bar complaint"],
  },
  {
    slug: "saratoga-springs",
    name: "Saratoga Springs",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Third Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad3/index.shtml",
    description: "Saratoga Springs, in Saratoga County in the Capital District region, is served by the Third Department Attorney Grievance Committee.",
    keywords: ["Saratoga Springs attorney ethics", "Saratoga County attorney misconduct", "Saratoga Springs lawyer discipline", "Capital District attorney investigation", "Third Department Saratoga"],
  },
  {
    slug: "ithaca",
    name: "Ithaca",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Third Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad3/index.shtml",
    description: "Ithaca, home to Cornell University and Ithaca College, has a legal community shaped by the university environment and Tompkins County needs. Attorney discipline falls under the Third Department.",
    keywords: ["Ithaca attorney ethics", "Tompkins County attorney misconduct", "Ithaca lawyer discipline", "Ithaca attorney investigation", "Cornell attorney ethics"],
  },
  {
    slug: "elmira",
    name: "Elmira",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Third Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad3/index.shtml",
    description: "Elmira, the seat of Chemung County in the Southern Tier, is served by the Third Department Attorney Grievance Committee for attorney discipline matters.",
    keywords: ["Elmira attorney ethics", "Chemung County attorney misconduct", "Elmira lawyer discipline", "Southern Tier attorney investigation", "Third Department attorney discipline"],
  },
  {
    slug: "plattsburgh",
    name: "Plattsburgh",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Third Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad3/index.shtml",
    description: "Plattsburgh, in Clinton County in the North Country, is served by the Third Department Attorney Grievance Committee for attorney discipline matters.",
    keywords: ["Plattsburgh attorney ethics", "Clinton County attorney misconduct", "Plattsburgh lawyer discipline", "North Country attorney investigation", "Third Department North Country"],
  },
  {
    slug: "watertown",
    name: "Watertown",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Fourth Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad4/index.shtml",
    description: "Watertown, the seat of Jefferson County in Northern New York, is served by the Fourth Department Attorney Grievance Committee for attorney discipline matters.",
    keywords: ["Watertown attorney ethics", "Jefferson County attorney misconduct", "Watertown lawyer discipline", "Northern New York attorney investigation", "Fourth Department attorney discipline"],
  },
  {
    slug: "garden-city",
    name: "Garden City",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Tenth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Garden City, in Nassau County, is a hub for legal practice on Long Island and is served by the Second Department Attorney Grievance Committee's Tenth Judicial District.",
    keywords: ["Garden City attorney ethics", "Garden City lawyer misconduct", "Nassau County attorney discipline Garden City", "Long Island attorney investigation", "Second Department Nassau"],
  },
  {
    slug: "hauppauge",
    name: "Hauppauge",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Tenth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Hauppauge, the seat of Suffolk County's government center, is a major hub for legal practice in Suffolk County and is served by the Second Department's Tenth Judicial District.",
    keywords: ["Hauppauge attorney ethics", "Suffolk County attorney discipline", "Hauppauge lawyer misconduct", "Long Island attorney investigation", "Second Department Suffolk Hauppauge"],
  },
  {
    slug: "mineola",
    name: "Mineola",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Tenth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Mineola, the county seat of Nassau County, is home to the Nassau County courthouse and a significant cluster of legal practitioners. Attorney discipline falls under the Second Department's Tenth Judicial District.",
    keywords: ["Mineola attorney ethics", "Nassau County courthouse attorney misconduct", "Mineola lawyer discipline", "Nassau County attorney investigation", "Second Department Mineola"],
  },
  {
    slug: "riverhead",
    name: "Riverhead",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Tenth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Riverhead, the county seat of Suffolk County, is a legal hub for the eastern Long Island region. Attorney discipline falls under the Second Department's Tenth Judicial District.",
    keywords: ["Riverhead attorney ethics", "Suffolk County courthouse attorney misconduct", "Riverhead lawyer discipline", "East Long Island attorney investigation", "Second Department Riverhead"],
  },
  {
    slug: "hempstead",
    name: "Hempstead",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Tenth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Hempstead, one of the largest villages in the United States, is in Nassau County and is served by the Second Department's Tenth Judicial District for attorney discipline.",
    keywords: ["Hempstead attorney ethics", "Hempstead lawyer misconduct", "Nassau County attorney discipline Hempstead", "Long Island attorney investigation Hempstead", "Second Department Nassau Hempstead"],
  },
  {
    slug: "rome-ny",
    name: "Rome",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Fourth Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad4/index.shtml",
    description: "Rome, in Oneida County in Central New York, is served by the Fourth Department Attorney Grievance Committee for attorney discipline matters.",
    keywords: ["Rome New York attorney ethics", "Oneida County attorney misconduct", "Rome NY lawyer discipline", "Central New York attorney investigation", "Fourth Department Oneida County"],
  },
  {
    slug: "jamestown",
    name: "Jamestown",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Fourth Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad4/index.shtml",
    description: "Jamestown, in Chautauqua County in Western New York, is served by the Fourth Department Attorney Grievance Committee for attorney discipline matters.",
    keywords: ["Jamestown attorney ethics", "Chautauqua County attorney misconduct", "Jamestown lawyer discipline", "Western New York attorney investigation", "Fourth Department Chautauqua"],
  },
  {
    slug: "glens-falls",
    name: "Glens Falls",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Third Department Attorney Grievance Committee",
    barUrl: "https://www.nycourts.gov/courts/ad3/index.shtml",
    description: "Glens Falls, in Warren County in the Adirondack region, is served by the Third Department Attorney Grievance Committee for attorney discipline matters.",
    keywords: ["Glens Falls attorney ethics", "Warren County attorney misconduct", "Glens Falls lawyer discipline", "Adirondack attorney investigation", "Third Department Warren County"],
  },
  {
    slug: "middletown-ny",
    name: "Middletown",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Middletown, in Orange County in the Hudson Valley, is served by the Second Department's Ninth Judicial District for attorney discipline matters.",
    keywords: ["Middletown New York attorney ethics", "Orange County attorney misconduct", "Middletown NY lawyer discipline", "Hudson Valley attorney investigation", "Second Department Orange County"],
  },
  {
    slug: "spring-valley",
    name: "Spring Valley",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Spring Valley, in Rockland County, is served by the Second Department's Ninth Judicial District for attorney discipline. The area's diverse immigrant community makes it a focus for immigration attorney misconduct coverage.",
    keywords: ["Spring Valley attorney ethics", "Rockland County attorney misconduct", "Spring Valley lawyer discipline", "Rockland County attorney investigation", "Second Department Rockland"],
  },
  {
    slug: "port-chester",
    name: "Port Chester",
    state: "New York",
    stateSlug: "new-york",
    barBody: "Second Department Attorney Grievance Committee — Ninth Judicial District",
    barUrl: "https://www.nycourts.gov/courts/ad2/AGC/index.shtml",
    description: "Port Chester, in Westchester County, is served by the Second Department's Ninth Judicial District for attorney discipline matters.",
    keywords: ["Port Chester attorney ethics", "Westchester attorney misconduct Port Chester", "Port Chester lawyer discipline", "Westchester County attorney investigation", "Second Department Westchester Port Chester"],
  },
  // Major cities from other states
  {
    slug: "los-angeles",
    name: "Los Angeles",
    state: "California",
    stateSlug: "california",
    barBody: "State Bar of California — Los Angeles County Bar Association",
    barUrl: "https://www.calbar.ca.gov/attorneys/discipline-disbarment",
    description: "Los Angeles is home to one of the largest concentrations of attorneys in the United States. The State Bar of California handles discipline for California attorneys, including the large Los Angeles legal community. The Ethics Reporter covers attorney misconduct across Los Angeles, from entertainment law fraud to immigration attorney exploitation of vulnerable populations.",
    keywords: ["Los Angeles attorney ethics", "Los Angeles lawyer misconduct", "California State Bar LA", "Los Angeles attorney discipline", "LA attorney investigation"],
  },
  {
    slug: "chicago",
    name: "Chicago",
    state: "Illinois",
    stateSlug: "illinois",
    barBody: "Illinois Attorney Registration & Disciplinary Commission (ARDC)",
    barUrl: "https://www.iardc.org/",
    description: "Chicago is the legal capital of Illinois and a major hub for commercial litigation, criminal defense, and immigration law. Attorney discipline in Illinois is handled by the Attorney Registration & Disciplinary Commission (ARDC). The Ethics Reporter covers attorney misconduct investigations involving Chicago attorneys.",
    keywords: ["Chicago attorney ethics", "Chicago lawyer misconduct", "Illinois ARDC discipline", "Chicago attorney discipline", "Illinois attorney investigation"],
  },
  {
    slug: "houston",
    name: "Houston",
    state: "Texas",
    stateSlug: "texas",
    barBody: "State Bar of Texas — Commission for Lawyer Discipline",
    barUrl: "https://www.texasbar.com/attorney-discipline",
    description: "Houston is one of the largest legal markets in the United States. Attorney discipline in Texas is handled by the Commission for Lawyer Discipline. The Ethics Reporter covers attorney misconduct in Houston, including cases involving the energy industry, personal injury, and immigration law.",
    keywords: ["Houston attorney ethics", "Houston lawyer misconduct", "Texas Bar Commission discipline", "Houston attorney discipline", "Texas attorney investigation Houston"],
  },
  {
    slug: "phoenix",
    name: "Phoenix",
    state: "Arizona",
    stateSlug: "arizona",
    barBody: "State Bar of Arizona — Attorney Discipline",
    barUrl: "https://www.azbar.org/for-the-public/attorney-discipline/",
    description: "Phoenix is the capital and largest city of Arizona and a major legal market. Attorney discipline in Arizona is handled by the State Bar of Arizona. The Ethics Reporter covers attorney misconduct investigations in Phoenix.",
    keywords: ["Phoenix attorney ethics", "Phoenix lawyer misconduct", "Arizona State Bar discipline", "Phoenix attorney discipline", "Arizona attorney investigation Phoenix"],
  },
  {
    slug: "philadelphia",
    name: "Philadelphia",
    state: "Pennsylvania",
    stateSlug: "pennsylvania",
    barBody: "Disciplinary Board of the Supreme Court of Pennsylvania",
    barUrl: "https://www.padisciplinaryboard.org/",
    description: "Philadelphia is Pennsylvania's largest city and a major legal market, home to federal courts, the Third Circuit Court of Appeals, and a large legal community. Attorney discipline in Pennsylvania is handled by the Disciplinary Board of the Supreme Court of Pennsylvania.",
    keywords: ["Philadelphia attorney ethics", "Philadelphia lawyer misconduct", "Pennsylvania Disciplinary Board Philadelphia", "Philadelphia attorney discipline", "Pennsylvania attorney investigation Philadelphia"],
  },
  {
    slug: "san-antonio",
    name: "San Antonio",
    state: "Texas",
    stateSlug: "texas",
    barBody: "State Bar of Texas — Commission for Lawyer Discipline",
    barUrl: "https://www.texasbar.com/attorney-discipline",
    description: "San Antonio is one of the largest cities in Texas and a significant legal market. Attorney discipline in Texas is handled by the Commission for Lawyer Discipline. The Ethics Reporter covers attorney misconduct in the San Antonio area.",
    keywords: ["San Antonio attorney ethics", "San Antonio lawyer misconduct", "Texas Bar Commission San Antonio", "San Antonio attorney discipline", "Texas attorney investigation San Antonio"],
  },
  {
    slug: "san-diego",
    name: "San Diego",
    state: "California",
    stateSlug: "california",
    barBody: "State Bar of California — San Diego County Bar Association",
    barUrl: "https://www.calbar.ca.gov/attorneys/discipline-disbarment",
    description: "San Diego is a major California legal market, particularly active in immigration law given its border location. Attorney discipline is handled by the State Bar of California. The Ethics Reporter covers attorney misconduct in San Diego, with particular attention to immigration attorney fraud.",
    keywords: ["San Diego attorney ethics", "San Diego lawyer misconduct", "California State Bar San Diego", "San Diego attorney discipline", "California attorney investigation San Diego"],
  },
  {
    slug: "dallas",
    name: "Dallas",
    state: "Texas",
    stateSlug: "texas",
    barBody: "State Bar of Texas — Commission for Lawyer Discipline",
    barUrl: "https://www.texasbar.com/attorney-discipline",
    description: "Dallas is one of the most active legal markets in the United States, with a large bar handling commercial, real estate, and personal injury matters. Attorney discipline in Texas is handled by the Commission for Lawyer Discipline.",
    keywords: ["Dallas attorney ethics", "Dallas lawyer misconduct", "Texas Bar Commission Dallas", "Dallas attorney discipline", "Texas attorney investigation Dallas"],
  },
  {
    slug: "jacksonville",
    name: "Jacksonville",
    state: "Florida",
    stateSlug: "florida",
    barBody: "The Florida Bar — Grievance Committees",
    barUrl: "https://www.floridabar.org/public/consumers/attorney-discipline/",
    description: "Jacksonville is the largest city in Florida by area and a major legal market. Attorney discipline in Florida is handled by The Florida Bar through local grievance committees. The Ethics Reporter covers attorney misconduct across Florida, including Jacksonville.",
    keywords: ["Jacksonville attorney ethics", "Jacksonville lawyer misconduct", "Florida Bar Jacksonville", "Jacksonville attorney discipline", "Florida attorney investigation Jacksonville"],
  },
  {
    slug: "austin",
    name: "Austin",
    state: "Texas",
    stateSlug: "texas",
    barBody: "State Bar of Texas — Commission for Lawyer Discipline",
    barUrl: "https://www.texasbar.com/attorney-discipline",
    description: "Austin, the capital of Texas, has a fast-growing legal market driven by the city's tech sector expansion. Attorney discipline in Texas is handled by the Commission for Lawyer Discipline.",
    keywords: ["Austin attorney ethics", "Austin lawyer misconduct", "Texas Bar Commission Austin", "Austin attorney discipline", "Texas attorney investigation Austin"],
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return citiesData.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return citiesData.map((c) => c.slug);
}
