export interface DefendStateData {
  name: string;
  slug: string;
  bar: string;
  medicalBoard: string;
  nursingBoard: string;
  cpaBoard: string;
  dentalBoard: string;
  pharmacyBoard: string;
  teachingBoard: string;
  engineeringBoard: string;
  cities: string[];
  uniqueRule: string;
}

export const defendStatesData: DefendStateData[] = [
  {
    name: "New York",
    slug: "new-york",
    bar: "Attorney Grievance Committees of the Appellate Division",
    medicalBoard: "New York State Board for Professional Medical Conduct (OPMC)",
    nursingBoard: "New York State Board of Nursing",
    cpaBoard: "New York State Board for Public Accountancy",
    dentalBoard: "New York State Board for Dentistry",
    pharmacyBoard: "New York State Board of Pharmacy",
    teachingBoard: "New York State Education Department, Office of Teaching Initiatives",
    engineeringBoard: "New York State Board for Engineering and Land Surveying",
    cities: ["New York City", "Buffalo", "Rochester", "Albany", "Syracuse"],
    uniqueRule: "New York's Rules of Professional Conduct (22 NYCRR Part 1200) impose particularly stringent obligations around trust account record-keeping (Rule 1.15), and OPMC physician investigations are governed by Public Health Law §230 — a process notoriously aggressive in its early subpoena stages.",
  },
  {
    name: "New Jersey",
    slug: "new-jersey",
    bar: "Office of Attorney Ethics, New Jersey Supreme Court",
    medicalBoard: "New Jersey State Board of Medical Examiners",
    nursingBoard: "New Jersey Board of Nursing",
    cpaBoard: "New Jersey State Board of Accountancy",
    dentalBoard: "New Jersey State Board of Dentistry",
    pharmacyBoard: "New Jersey State Board of Pharmacy",
    teachingBoard: "New Jersey Department of Education, Office of Certification and Induction",
    engineeringBoard: "New Jersey State Board of Professional Engineers and Land Surveyors",
    cities: ["Newark", "Jersey City", "Paterson", "Trenton", "Edison"],
    uniqueRule: "New Jersey is the only state with a centralized Office of Attorney Ethics that supervises district ethics committees statewide, and random trust-account audits under R. 1:21-6 are a uniquely aggressive enforcement mechanism.",
  },
  {
    name: "Rhode Island",
    slug: "rhode-island",
    bar: "Disciplinary Board of the Rhode Island Supreme Court",
    medicalBoard: "Rhode Island Board of Medical Licensure and Discipline",
    nursingBoard: "Rhode Island Board of Nurse Registration and Nursing Education",
    cpaBoard: "Rhode Island Board of Accountancy",
    dentalBoard: "Rhode Island Board of Examiners in Dentistry",
    pharmacyBoard: "Rhode Island Board of Pharmacy",
    teachingBoard: "Rhode Island Department of Education, Office of Educator Excellence and Certification",
    engineeringBoard: "Rhode Island Board of Registration for Professional Engineers",
    cities: ["Providence", "Warwick", "Cranston", "Pawtucket", "East Providence"],
    uniqueRule: "Rhode Island is a small jurisdiction where reputational damage from disciplinary action is amplified — and the Supreme Court's Disciplinary Counsel maintains broad investigative discretion under Article III of the Supreme Court Rules.",
  },
  {
    name: "Maine",
    slug: "maine",
    bar: "Board of Overseers of the Bar",
    medicalBoard: "Maine Board of Licensure in Medicine",
    nursingBoard: "Maine State Board of Nursing",
    cpaBoard: "Maine Board of Accountancy",
    dentalBoard: "Maine Board of Dental Practice",
    pharmacyBoard: "Maine Board of Pharmacy",
    teachingBoard: "Maine Department of Education, Certification Office",
    engineeringBoard: "Maine Board of Licensure for Professional Engineers",
    cities: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
    uniqueRule: "Maine grievance procedures are governed by the Maine Bar Rules with screening, investigation, and Grievance Commission Panel review stages — and tight 21-day response windows once a complaint is docketed.",
  },
  {
    name: "Massachusetts",
    slug: "massachusetts",
    bar: "Board of Bar Overseers / Office of Bar Counsel",
    medicalBoard: "Massachusetts Board of Registration in Medicine",
    nursingBoard: "Massachusetts Board of Registration in Nursing",
    cpaBoard: "Massachusetts Board of Public Accountancy",
    dentalBoard: "Massachusetts Board of Registration in Dentistry",
    pharmacyBoard: "Massachusetts Board of Registration in Pharmacy",
    teachingBoard: "Massachusetts Department of Elementary and Secondary Education, Office of Educator Licensure",
    engineeringBoard: "Massachusetts Board of Registration of Professional Engineers and Professional Land Surveyors",
    cities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
    uniqueRule: "Massachusetts Bar Counsel screens complaints aggressively under SJC Rule 4:01 — and Board of Registration in Medicine investigations include mandatory reporting from hospitals under M.G.L. c. 111, §53B that often trigger parallel proceedings.",
  },
  {
    name: "North Dakota",
    slug: "north-dakota",
    bar: "Disciplinary Board of the North Dakota Supreme Court",
    medicalBoard: "North Dakota Board of Medicine",
    nursingBoard: "North Dakota Board of Nursing",
    cpaBoard: "North Dakota State Board of Accountancy",
    dentalBoard: "North Dakota State Board of Dental Examiners",
    pharmacyBoard: "North Dakota State Board of Pharmacy",
    teachingBoard: "North Dakota Education Standards and Practices Board",
    engineeringBoard: "North Dakota State Board of Registration for Professional Engineers and Land Surveyors",
    cities: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
    uniqueRule: "North Dakota's small bar means disciplinary matters frequently reach Supreme Court review, and the Education Standards and Practices Board uses an investigatory model that can suspend a teaching license on emergency grounds before a hearing.",
  },
  {
    name: "Illinois",
    slug: "illinois",
    bar: "Attorney Registration and Disciplinary Commission (ARDC)",
    medicalBoard: "Illinois Department of Financial and Professional Regulation, Medical Disciplinary Board",
    nursingBoard: "Illinois Board of Nursing",
    cpaBoard: "Illinois Board of Examiners / Public Accountant Registration Committee",
    dentalBoard: "Illinois State Board of Dentistry",
    pharmacyBoard: "Illinois State Board of Pharmacy",
    teachingBoard: "Illinois State Board of Education, Educator Effectiveness Department",
    engineeringBoard: "Illinois Professional Engineering Licensing Board",
    cities: ["Chicago", "Aurora", "Naperville", "Joliet", "Rockford"],
    uniqueRule: "The Illinois ARDC is one of the most aggressive bar regulators in the country, with a published searchable database of every disciplined attorney; IDFPR investigations of physicians and nurses are also fast-moving and can trigger automatic summary suspension under 225 ILCS 60/22.",
  },
  {
    name: "Vermont",
    slug: "vermont",
    bar: "Professional Responsibility Board, Vermont Supreme Court",
    medicalBoard: "Vermont Board of Medical Practice",
    nursingBoard: "Vermont State Board of Nursing",
    cpaBoard: "Vermont Board of Public Accountancy",
    dentalBoard: "Vermont Board of Dental Examiners",
    pharmacyBoard: "Vermont Board of Pharmacy",
    teachingBoard: "Vermont Agency of Education, Educator Quality Division",
    engineeringBoard: "Vermont Board of Professional Engineering",
    cities: ["Burlington", "South Burlington", "Rutland", "Essex Junction", "Montpelier"],
    uniqueRule: "Vermont's Administrative Order 9 governs attorney discipline, and the Office of Professional Regulation oversees nearly all non-attorney licensed professions — meaning a single Office investigates and prosecutes most professional complaints.",
  },
  {
    name: "Pennsylvania",
    slug: "pennsylvania",
    bar: "Disciplinary Board of the Supreme Court of Pennsylvania / Office of Disciplinary Counsel",
    medicalBoard: "Pennsylvania State Board of Medicine",
    nursingBoard: "Pennsylvania State Board of Nursing",
    cpaBoard: "Pennsylvania State Board of Accountancy",
    dentalBoard: "Pennsylvania State Board of Dentistry",
    pharmacyBoard: "Pennsylvania State Board of Pharmacy",
    teachingBoard: "Pennsylvania Department of Education, Professional Standards and Practices Commission",
    engineeringBoard: "Pennsylvania State Registration Board for Professional Engineers, Land Surveyors and Geologists",
    cities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"],
    uniqueRule: "Pennsylvania's Rules of Disciplinary Enforcement (Pa.R.D.E.) provide a multi-stage process — Disciplinary Counsel, Hearing Committee, Board, and Supreme Court review — and the Educator Discipline Act (24 P.S. §§ 2070.1a et seq.) creates a specific regime for teacher misconduct.",
  },
  {
    name: "Texas",
    slug: "texas",
    bar: "Office of the Chief Disciplinary Counsel, State Bar of Texas",
    medicalBoard: "Texas Medical Board",
    nursingBoard: "Texas Board of Nursing",
    cpaBoard: "Texas State Board of Public Accountancy",
    dentalBoard: "Texas State Board of Dental Examiners",
    pharmacyBoard: "Texas State Board of Pharmacy",
    teachingBoard: "Texas Education Agency, Educator Investigations Division",
    engineeringBoard: "Texas Board of Professional Engineers and Land Surveyors",
    cities: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth"],
    uniqueRule: "Texas attorneys can elect to have grievances heard by an evidentiary panel of the District Grievance Committee or in district court under the Texas Rules of Disciplinary Procedure — a strategic choice with major consequences. The Texas Medical Board is one of the most active in the nation in license actions.",
  },
  {
    name: "Florida",
    slug: "florida",
    bar: "The Florida Bar, Lawyer Regulation Department",
    medicalBoard: "Florida Board of Medicine",
    nursingBoard: "Florida Board of Nursing",
    cpaBoard: "Florida Board of Accountancy",
    dentalBoard: "Florida Board of Dentistry",
    pharmacyBoard: "Florida Board of Pharmacy",
    teachingBoard: "Florida Department of Education, Office of Professional Practices Services",
    engineeringBoard: "Florida Board of Professional Engineers",
    cities: ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg"],
    uniqueRule: "Florida Bar grievances are governed by Chapter 3 of the Rules Regulating The Florida Bar, with a unified statewide grievance committee structure. The Department of Health prosecutes nearly all healthcare licensees through the Division of Medical Quality Assurance — a single agency with broad investigative authority.",
  },
];

export const professionsData = [
  {
    slug: "attorney",
    name: "Attorney",
    plural: "Attorneys",
    boardKey: "bar" as const,
    boardLabel: "state bar disciplinary authority",
    commonViolations: [
      "Trust account / IOLTA mismanagement and commingling of client funds",
      "Failure to communicate with clients (Rule 1.4 violations)",
      "Conflicts of interest, including concurrent and former-client conflicts",
      "Missed statutes of limitation and other deadlines",
      "Unauthorized practice of law in another jurisdiction",
      "Fee disputes and excessive fees",
      "Dishonesty, fraud, or misrepresentation (Rule 8.4(c))",
      "Criminal conduct reflecting on fitness to practice",
    ],
    consequences: "Disciplinary outcomes range from private admonition, public reprimand, and probation, to suspension and disbarment. Many states also impose restitution, CLE requirements, and mandatory practice monitoring.",
  },
  {
    slug: "doctor",
    name: "Doctor",
    plural: "Doctors",
    boardKey: "medicalBoard" as const,
    boardLabel: "state medical board",
    commonViolations: [
      "Allegations of medical negligence or substandard care",
      "Improper prescribing of controlled substances",
      "Failure to maintain adequate medical records",
      "Boundary violations or inappropriate relationships with patients",
      "Substance use disorder allegations",
      "Insurance and billing fraud",
      "Failure to obtain informed consent",
      "Sexual misconduct allegations",
    ],
    consequences: "Sanctions can include letters of concern, fines, mandated CME, practice restrictions, supervised practice, suspension, and license revocation. Hospital privileges and DEA registrations are typically affected, and the National Practitioner Data Bank (NPDB) report follows physicians for life.",
  },
  {
    slug: "nurse",
    name: "Nurse",
    plural: "Nurses",
    boardKey: "nursingBoard" as const,
    boardLabel: "state board of nursing",
    commonViolations: [
      "Medication errors and diversion",
      "Substance use disorder",
      "Practicing outside the scope of licensure",
      "Falsification of patient records",
      "Patient abandonment",
      "Boundary violations",
      "Criminal convictions (including DUIs)",
      "Failure to report a colleague's misconduct",
    ],
    consequences: "Nursing boards can issue letters of concern, fines, remedial education, practice limitations, suspension, and revocation. Most boards also report adverse actions to NURSYS, which makes the discipline visible to every state where the nurse holds or seeks a license.",
  },
  {
    slug: "cpa",
    name: "CPA",
    plural: "CPAs",
    boardKey: "cpaBoard" as const,
    boardLabel: "state board of accountancy",
    commonViolations: [
      "Audit failures and GAAS violations",
      "Independence violations under AICPA rules",
      "Failure to file or fraudulently filing client tax returns",
      "Misappropriation of client funds",
      "Lack of due professional care",
      "Disciplinary action by the SEC, PCAOB, or IRS Office of Professional Responsibility",
      "Confidentiality breaches",
      "Failing peer review",
    ],
    consequences: "State boards can impose fines, mandatory CPE, practice restrictions, suspension, and revocation of the CPA license and firm permit. Federal action by the SEC or PCAOB triggers parallel state board proceedings in nearly every case.",
  },
  {
    slug: "dentist",
    name: "Dentist",
    plural: "Dentists",
    boardKey: "dentalBoard" as const,
    boardLabel: "state board of dental examiners",
    commonViolations: [
      "Substandard care or unnecessary procedures",
      "Improper sedation practices",
      "Inadequate sterilization and infection control",
      "Insurance fraud and upcoding",
      "Improper prescribing of controlled substances",
      "Practicing outside scope of licensure (e.g., orthodontics or implants without proper credentials)",
      "Inadequate informed consent",
      "Boundary violations",
    ],
    consequences: "Dental boards can require remedial education, restrict procedures (e.g., revoke sedation permits), impose probation, suspend, or revoke the license. Findings are reported to the National Practitioner Data Bank.",
  },
  {
    slug: "pharmacist",
    name: "Pharmacist",
    plural: "Pharmacists",
    boardKey: "pharmacyBoard" as const,
    boardLabel: "state board of pharmacy",
    commonViolations: [
      "Drug diversion and theft of controlled substances",
      "Dispensing errors causing patient harm",
      "Filling forged or fraudulent prescriptions",
      "Practicing under the influence",
      "Recordkeeping violations under DEA and state law",
      "Compounding violations under USP <795> and <797>",
      "Insurance fraud",
      "Failure to perform required drug utilization reviews",
    ],
    consequences: "Boards can impose fines, mandate remediation programs, restrict controlled substance handling, suspend, or revoke the pharmacist license. DEA registration is almost always affected when controlled substances are involved.",
  },
  {
    slug: "teacher",
    name: "Teacher",
    plural: "Teachers",
    boardKey: "teachingBoard" as const,
    boardLabel: "state department of education / educator licensing board",
    commonViolations: [
      "Inappropriate communication or relationships with students",
      "Boundary violations (including social media)",
      "Allegations of corporal punishment or excessive discipline",
      "Test security violations (compromising standardized testing)",
      "Falsification of credentials or grades",
      "Off-duty criminal conduct",
      "Substance use on school grounds",
      "Failure to report suspected child abuse",
    ],
    consequences: "Outcomes range from a letter of admonishment, mandated training, probation, suspension, and permanent revocation. Most states report disciplinary actions to the NASDTEC Educator Identification Clearinghouse, which all 50 states consult before licensing a teacher from out of state.",
  },
  {
    slug: "engineer",
    name: "Engineer",
    plural: "Engineers",
    boardKey: "engineeringBoard" as const,
    boardLabel: "state board of professional engineers",
    commonViolations: [
      "Sealing or signing plans not prepared under direct supervision",
      "Negligent design leading to failure or safety risk",
      "Practicing outside area of competence",
      "Conflicts of interest on public projects",
      "Failure to report code violations or unsafe conditions",
      "Misrepresentation of credentials",
      "Unlicensed practice or holding out as a PE without licensure",
      "Plan-stamping for unlicensed designers",
    ],
    consequences: "State engineering boards can impose civil penalties, mandate continuing education, censure, suspend, or revoke the PE license. Many actions are reported to NCEES and the Council Records Program, which affects licensure in every other state.",
  },
];

export type ProfessionData = (typeof professionsData)[number];
