export interface TopicData {
  slug: string;
  title: string;
  description: string;
  intro: string;
  keywords: string[];
}

export const topicsData: TopicData[] = [
  {
    slug: "ai-in-legal-practice",
    title: "AI in Legal Practice: Sanctions, Risks & the Future of Law",
    description: "How courts are sanctioning attorneys for AI hallucinations, the growing crackdown on artificial intelligence in legal filings, and what it means for the future of the legal profession.",
    intro: "Artificial intelligence has arrived in the courtroom — and the legal profession is in crisis over how to respond. Courts across the country are imposing heavy sanctions on attorneys who submit AI-generated legal work containing fabricated citations, nonexistent cases, and hallucinated statutes. The Ethics Reporter covers every major AI sanctions case, exploring not just the individual attorney misconduct but the broader institutional question: is the legal profession using AI sanctions as a tool to protect its gatekeeping power against technological disruption? Our coverage examines the real costs of AI hallucinations in legal filings, the growing patchwork of court AI disclosure rules, and the fundamental question of whether the legal profession will adapt to artificial intelligence or try to regulate it out of existence.",
    keywords: ["AI in legal practice", "attorney AI sanctions", "AI hallucinations law", "ChatGPT legal citations", "lawyer artificial intelligence"],
  },
  {
    slug: "client-fund-misappropriation",
    title: "Client Fund Misappropriation: When Lawyers Steal",
    description: "Coverage of attorney theft, IOLTA trust account violations, and the cases where lawyers steal from the very clients who trusted them.",
    intro: "Among the most serious violations of the attorney-client relationship is the theft of client funds. Attorneys hold client money in trust — in IOLTA (Interest on Lawyers Trust Accounts) accounts specifically designed to separate client funds from attorney funds. When lawyers dip into those accounts for personal use, the consequences range from disbarment to criminal prosecution. The Ethics Reporter investigates client fund misappropriation cases across the country, tracking the attorneys who steal from vulnerable clients, the disciplinary systems that are supposed to catch them, and the Client Protection Funds that attempt to make victims whole. Our coverage asks why so many attorneys steal client money, why the discipline system often catches them too late, and what victims can do when their lawyer has stolen from them.",
    keywords: ["lawyer stole money", "attorney client fund theft", "IOLTA misappropriation", "attorney disbarred stealing", "client fund misappropriation"],
  },
  {
    slug: "judicial-misconduct",
    title: "Judicial Misconduct: When Judges Break the Rules",
    description: "Investigations into judicial misconduct, bias, corruption, and the largely secretive system that is supposed to hold judges accountable.",
    intro: "Judges occupy a position of extraordinary power in American society. They decide cases involving life, liberty, and property with enormous discretion and minimal oversight. When judges abuse that power — through bias, corruption, improper conduct, or simple incompetence — the consequences for the litigants before them can be catastrophic. The Ethics Reporter investigates judicial misconduct cases across the country, examining the conduct itself, the often-inadequate disciplinary response, and the systemic failures that allow bad judges to remain on the bench for years. Our coverage is informed by the Founders' vision of an accountable judiciary — a vision that has been steadily undermined by a self-policing system that prioritizes judicial independence over public accountability.",
    keywords: ["judicial misconduct", "judge discipline", "judge removed from bench", "corrupt judge", "judicial conduct commission"],
  },
  {
    slug: "disbarment",
    title: "Disbarment: The Ultimate Attorney Discipline",
    description: "Coverage of attorney disbarment cases across the country — the most serious sanction the legal profession can impose on its own members.",
    intro: "Disbarment is the permanent revocation of an attorney's license to practice law. It is the most serious sanction the legal profession can impose, reserved for the most egregious misconduct: stealing from clients, committing fraud, engaging in criminal conduct, or demonstrating repeated and willful disregard for professional obligations. The Ethics Reporter tracks disbarment cases across all 50 states, examining the conduct that led to disbarment, the disciplinary proceedings that produced it, and what disbarment actually means for the attorneys and the clients they harmed. We also examine the cases where disbarment should have happened sooner — where gradual escalation through lesser sanctions allowed attorneys to continue harming clients long after the writing was on the wall.",
    keywords: ["attorney disbarred", "disbarment cases", "lawyer disbarred", "attorney license revoked", "permanent disbarment"],
  },
  {
    slug: "attorney-suspension",
    title: "Attorney Suspension: Cases & Consequences",
    description: "Coverage of attorney suspension cases — the temporary removal of law licenses for professional misconduct across the United States.",
    intro: "Attorney suspension — the temporary removal of a lawyer's license to practice law — is the middle ground of attorney discipline, more serious than a public censure but less permanent than disbarment. Suspension periods range from 30 days to several years, and they carry serious consequences: the attorney cannot represent clients, must notify existing clients, and must apply for reinstatement after the suspension period ends. The Ethics Reporter covers suspension cases across the country, examining the conduct that prompted discipline, the proportionality of the sanction, and what happens to the clients whose lawyers are suspended mid-representation. We also track patterns in suspension cases — which types of misconduct most commonly lead to suspension, and whether the discipline system uses suspension appropriately or too sparingly.",
    keywords: ["attorney suspended", "lawyer suspension", "law license suspended", "attorney discipline", "suspended from practice"],
  },
  {
    slug: "law-school-debt-crisis",
    title: "The Law School Debt Crisis: A Profession in Decline",
    description: "Investigating the law school industrial complex — the institutions charging $300,000 for degrees that lead to unemployment, debt, and a profession being automated out of existence.",
    intro: "Law school has become one of the most expensive professional degrees in the United States, with total costs at many institutions exceeding $300,000. Yet the legal job market has struggled to absorb the number of graduates law schools produce, bar passage rates are declining, and artificial intelligence is beginning to automate the work that entry-level lawyers have historically performed. The Ethics Reporter investigates the law school debt crisis through the lens of institutional accountability: who is responsible for selling students on a credential that may not deliver the promised career? We examine law school enrollment numbers, employment statistics, bar passage rates, and the uncomfortable reality that AI is making significant portions of legal work — research, document review, contract drafting — increasingly automated. The question we ask is one that law schools are not: are these institutions selling a credential they know to be declining in value?",
    keywords: ["law school debt", "law school cost", "law school employment", "JD degree worth it", "law school AI disruption"],
  },
  {
    slug: "legal-ethics-reform",
    title: "Legal Ethics Reform: Fixing a Broken System",
    description: "The case for reforming attorney discipline, judicial accountability, and the self-policing systems that protect the legal profession at the expense of the public.",
    intro: "The American legal profession regulates itself — a privilege granted on the assumption that the profession will use regulatory power to protect the public rather than its own interests. That assumption is increasingly difficult to defend. State bar discipline systems dismiss the overwhelming majority of complaints without investigation. Judicial conduct commissions conduct proceedings in secret and rarely impose meaningful sanctions. The legal profession's response to AI is to impose disclosure requirements on attorneys while exempting judges from the same requirements. The Ethics Reporter covers the growing movement for legal ethics reform — the academics, advocates, and policymakers pushing for structural changes to attorney discipline, judicial accountability, and access to justice. We examine reform proposals through the lens of the public interest, asking whether the changes being proposed would actually make the legal system more accountable, more accessible, and more just.",
    keywords: ["legal ethics reform", "attorney discipline reform", "judicial accountability", "bar complaint reform", "legal profession regulation"],
  },
  {
    slug: "founding-fathers-judiciary",
    title: "The Founders vs. Today's Judiciary: A Constitutional Crisis",
    description: "How the American judiciary has drifted from the vision of the Founding Fathers — and what the Founders' own words tell us about the crisis in our legal system today.",
    intro: "The Founding Fathers were acutely aware of the dangers of an unaccountable judiciary. Jefferson warned that federal judges would work 'like gravity by night and by day' to expand their power. Madison insisted that no branch of government could be trusted to police itself. Hamilton promised that the judiciary would be staffed by men of 'integrity and moderation' — a promise that the intervening centuries have put to the test. The Ethics Reporter's Take America Back series examines the American legal system through the lens of the Founders' vision — asking not just what is happening in our courts today, but whether it comports with the constitutional design the Founders intended. We draw on primary sources: the Federalist Papers, Jefferson's letters, Madison's notes from the Constitutional Convention, and the text of the Constitution itself. The case we make is not partisan: the Founders' concerns about judicial overreach, professional self-dealing, and the corruption of institutions apply equally regardless of political affiliation.",
    keywords: ["founding fathers judiciary", "constitutional crisis courts", "judicial accountability founding", "Hamilton judiciary", "Jefferson courts"],
  },
  {
    slug: "attorney-discipline-explained",
    title: "How Attorney Discipline Works: A Complete Guide",
    description: "A comprehensive guide to the attorney discipline system — how complaints are filed, investigated, and resolved, and what the process actually looks like for complainants.",
    intro: "Most people who have been harmed by an attorney's misconduct do not know how the discipline system works, what to expect from a bar complaint, or whether the process will result in any meaningful accountability. The Ethics Reporter provides comprehensive coverage of the attorney discipline system — how it is structured, how it actually functions in practice, and what complainants can realistically expect. We cover the intake process, the investigation stage, the hearing process, and the range of sanctions available. We also cover the system's significant limitations: the high dismissal rate, the slow pace of proceedings, the confidentiality that shields much of the process from public view, and the ways that well-resourced attorneys can use procedural mechanisms to delay or avoid accountability. Our goal is to inform complainants about what they are getting into — and to hold the system accountable for the gap between its stated purpose and its actual performance.",
    keywords: ["how attorney discipline works", "bar complaint process", "attorney discipline system", "file complaint against lawyer", "attorney misconduct reporting"],
  },
  {
    slug: "ai-sanctions-attorneys",
    title: "AI Sanctions Against Attorneys: The Growing Crackdown",
    description: "Tracking every major court sanction imposed on attorneys for using AI to generate fake legal citations — and asking whether the crackdown is really about accuracy or professional gatekeeping.",
    intro: "Courts across the United States are imposing sanctions on attorneys who submit legal filings containing citations to cases that do not exist — fabrications generated by AI language models like ChatGPT and Claude. The sanctions have been severe: fines reaching $10,000 or more, orders to show cause, dismissal of cases, referrals to state bar disciplinary authorities, and in some cases suspension proceedings. The Ethics Reporter tracks every major AI sanctions case, from the first high-profile incident in the Mata v. Avianca case to the growing wave of sanctions in 2025 and 2026. We examine the cases in detail — who the attorneys were, what AI tools they used, what fabrications appeared in their filings, and what sanctions resulted. But we also ask the harder question: are these sanctions proportionate, or are courts using AI misconduct as an opportunity to make an example of attorneys in ways that serve institutional interests rather than justice?",
    keywords: ["AI sanctions lawyer", "ChatGPT fake citations attorney", "AI hallucination legal filing", "attorney sanctioned AI", "fake case citations lawyer"],
  },
  // --- NEW TOPICS ADDED FOR SEO EXPANSION ---
  {
    slug: "virtual-office-ethics",
    title: "Virtual Office Ethics: When Attorney Addresses Are a Mirage",
    description: "Attorneys using virtual mailboxes and coworking spaces to fake physical office presence, violating New York Judiciary Law §470 and misleading clients about where their lawyer actually works.",
    intro: "New York Judiciary Law §470 requires every attorney admitted to practice in New York to maintain an actual, physical office for the transaction of law business within the state. The requirement is not a technicality — it exists to ensure clients have a genuine point of contact with their attorney. But a growing number of New York attorneys list virtual mailboxes, coworking memberships, and shared desk arrangements as their \"offices,\" creating the appearance of a real law practice where none exists. The Ethics Reporter has investigated multiple attorneys whose listed office addresses are confirmed virtual mailbox services, including the investigation of Ernestas Pravilionis and EPRA Legal, whose three New York \"offices\" all appear to be virtual services. This topic covers §470 violations, the New York Court of Appeals' interpretation of the physical office requirement, and how prospective clients can verify whether their attorney's office is real.",
    keywords: ["virtual office attorney New York", "Judiciary Law 470", "attorney virtual mailbox", "fake law office address", "attorney ethics virtual office"],
  },
  {
    slug: "attorney-advertising-violations",
    title: "Attorney Advertising Violations: Fake Photos, False Claims, and Rule 7.1",
    description: "How attorneys violate Rule 7.1 of the Rules of Professional Conduct through misleading advertising — including AI-generated photos, fake credentials, and deceptive claims about experience.",
    intro: "Rule 7.1 of the New York Rules of Professional Conduct prohibits attorney advertising that is false, deceptive, or misleading. The rule exists because potential clients rely on attorney advertising when making one of the most consequential decisions of their lives: who will represent them in court, in immigration proceedings, in business disputes, or in criminal matters. Yet attorney advertising violations are endemic — from AI-generated headshots that misrepresent the attorney's appearance to exaggerated claims of experience, fake reviews, and misleading comparisons to competitors. The Ethics Reporter investigates Rule 7.1 violations across the country, with particular focus on New York attorneys whose advertising practices raise serious questions about the honesty and transparency that the rules require.",
    keywords: ["attorney advertising violations", "Rule 7.1 ethics", "false attorney advertising", "misleading lawyer website", "attorney ethics advertising"],
  },
  {
    slug: "attorney-competence-violations",
    title: "Attorney Competence Violations: When Lawyers Practice Beyond Their Ability",
    description: "Rule 1.1 of the Rules of Professional Conduct requires attorneys to provide competent representation. We investigate cases where attorneys take on complex matters they are not qualified to handle.",
    intro: "Rule 1.1 of the professional conduct rules — the competence rule — requires every attorney to bring to each representation the legal knowledge, skill, thoroughness, and preparation reasonably necessary for the matter. It is perhaps the most fundamental of all attorney obligations, and one of the most frequently violated. Newly admitted attorneys who take on asylum cases, complex litigation, or EB-1 petitions without adequate supervision are putting clients at risk. Attorneys who expand into new practice areas without learning the relevant law are violating Rule 1.1 with every representation they undertake. The Ethics Reporter investigates competence violations across the country, examining the cases where attorneys' lack of knowledge or preparation caused real harm to real clients.",
    keywords: ["attorney competence violations", "Rule 1.1 ethics", "lawyer incompetence", "attorney malpractice competence", "attorney practicing outside expertise"],
  },
  {
    slug: "ai-generated-attorney-photos",
    title: "AI-Generated Attorney Photos: The New Frontier of Legal Deception",
    description: "Attorneys using AI-generated headshots and synthetic images to misrepresent their appearance to clients — and why this practice may violate attorney advertising rules.",
    intro: "A growing number of law firms and solo practitioners are using AI-generated images — synthetic photographs created by artificial intelligence — to represent themselves on their websites and in advertising materials. In some cases, the disclosed attorney's photograph may not be a real photograph at all. In our investigation of Ernestas Pravilionis and EPRA Legal, we found a disclosure buried at the bottom of the About page stating that the website 'employs AI-generated images to depict the lawyer.' A client choosing an attorney is making a consequential decision in which the visual impression of who will represent them is a material factor — and presenting a fictional AI image as if it were a real photograph may constitute exactly the kind of false impression that attorney advertising rules prohibit. This topic covers the growing use of AI-generated images in attorney marketing, the regulatory framework that applies, and how clients can identify AI-generated photographs.",
    keywords: ["AI-generated attorney photos", "fake attorney headshot", "AI lawyer images", "attorney advertising AI photos", "synthetic attorney photograph"],
  },
  {
    slug: "new-attorney-misconduct",
    title: "New Attorney Misconduct: The Risks of Inexperienced Lawyers",
    description: "Newly admitted attorneys taking on complex legal matters without adequate experience or supervision — and the clients who pay the price for their overreach.",
    intro: "The transition from law school graduate to competent practicing attorney requires more than bar admission. It requires supervised experience, mentorship, and the gradual accumulation of practical knowledge that no law school curriculum can fully provide. When newly admitted attorneys take on complex immigration cases, high-stakes litigation, or specialized transactional matters without adequate preparation, clients suffer the consequences — incorrect legal arguments, missed deadlines, improper procedures, and outcomes that experienced counsel might have avoided. The Ethics Reporter tracks cases involving newly admitted attorneys whose clients were harmed by inexperience, examining what the rules require in terms of supervision and competence, and what happens when those requirements are ignored.",
    keywords: ["new attorney misconduct", "inexperienced lawyer", "newly admitted attorney ethics", "attorney supervision ethics", "new lawyer malpractice"],
  },
  {
    slug: "multi-practice-area-attorneys",
    title: "The Jack of All Trades Attorney: Competence Concerns in Multi-Practice Firms",
    description: "Attorneys claiming expertise across 10 or more practice areas simultaneously — and why this raises serious Rule 1.1 competence concerns for clients.",
    intro: "Every major area of law — immigration, litigation, intellectual property, criminal defense, real estate, estate planning — represents a distinct and complex body of statutory law, regulatory guidance, and case law built up over decades. Experienced attorneys typically specialize because depth matters in legal representation. Yet a growing segment of solo practitioners and small firms advertise competence across a dozen or more practice areas simultaneously, creating the impression of a generalist superattorney who can handle anything. In our investigation of EPRA Legal, we found an attorney two years out of bar admission advertising simultaneous expertise in asylum law, EB-1 petitions, civil litigation, intellectual property, corporate formation, consumer protection, and more. This topic examines when multi-practice-area advertising crosses the line from legitimate generalism into competence misrepresentation.",
    keywords: ["attorney multi practice area competence", "generalist lawyer ethics", "attorney advertising all practice areas", "Rule 1.1 multi practice", "lawyer competence advertising"],
  },
  {
    slug: "new-york-attorney-ethics",
    title: "New York Attorney Ethics: Discipline, Grievances, and the Appellate Division",
    description: "New York-specific attorney ethics coverage — Appellate Division grievance committees, how discipline works in New York, and investigations into New York attorneys.",
    intro: "New York's attorney discipline system is divided among four Appellate Division departments, each with its own grievance committees that investigate complaints against attorneys. The First Department covers Manhattan and the Bronx; the Second Department covers Brooklyn, Queens, Staten Island, and surrounding counties; the Third and Fourth Departments cover upstate New York. Each department processes thousands of complaints each year, and the vast majority are dismissed without public discipline. The Ethics Reporter covers attorney ethics in New York with particular focus on cases that reveal systemic problems: attorneys who practice without real offices, newly admitted lawyers who take on complex matters without supervision, and the gap between the rules as written and the rules as enforced.",
    keywords: ["New York attorney ethics", "New York bar discipline", "Appellate Division grievance committee", "New York attorney misconduct", "New York bar complaint"],
  },
  {
    slug: "attorney-website-fraud",
    title: "Attorney Website Fraud: Fake Credentials, False Claims, and Deceptive Marketing",
    description: "Attorneys whose websites misrepresent their experience, credentials, office locations, and the nature of their practice — and the ethics rules designed to prevent such deception.",
    intro: "An attorney's website is often a prospective client's first and most important impression of the lawyer they are considering hiring. For this reason, attorney advertising rules impose strict requirements on the accuracy and truthfulness of website representations. Yet attorney website fraud is disturbingly common: fake office locations designed to suggest a larger practice, inflated experience claims, misleading descriptions of credentials, photographs of attorneys who may not look as depicted, and endorsements or ratings that do not mean what the website implies. The Ethics Reporter investigates attorney websites that appear to cross the line from aggressive marketing into actionable misrepresentation, helping prospective clients make informed decisions about who they hire.",
    keywords: ["attorney website fraud", "misleading lawyer website", "fake attorney credentials online", "attorney ethics website", "attorney advertising deception"],
  },
  {
    slug: "appellate-division-grievance",
    title: "New York Appellate Division Grievance Committees: How to File a Bar Complaint",
    description: "A complete guide to the four New York Appellate Division Attorney Grievance Committees — how to file a complaint, what to expect, and what the process actually delivers.",
    intro: "New York divides attorney discipline among four Appellate Division departments, each maintaining its own Attorney Grievance Committee (AGC) or Departmental Disciplinary Committee (DDC). Complainants who have been harmed by attorney misconduct must file with the committee in the judicial department where the attorney maintains their principal office — a threshold requirement that confuses many people who want to hold their lawyer accountable. The First Department DDC handles Manhattan and the Bronx attorneys; the Second Department AGC handles Brooklyn, Queens, Staten Island, Nassau, Suffolk, Westchester, and surrounding counties; the Third and Fourth Departments cover upstate New York. This topic provides comprehensive guidance on filing with each committee, what the investigation process looks like, and what outcomes are realistic.",
    keywords: ["Appellate Division grievance committee New York", "DDC attorney grievance New York", "how to file bar complaint New York", "First Department disciplinary committee", "Second Department grievance committee"],
  },
  {
    slug: "bar-complaint-guide",
    title: "How to File a Bar Complaint Against an Attorney: A Complete Guide",
    description: "Step-by-step guidance on filing a bar complaint against an attorney in any state — what information you need, how the process works, and what to realistically expect.",
    intro: "Filing a bar complaint against an attorney is often the only formal recourse available to clients who have been harmed by lawyer misconduct. Yet most people who have been victimized by an attorney's unethical behavior do not know how the complaint process works, what information they need to provide, or what outcomes are realistically available. This guide explains the bar complaint process from start to finish: how to identify the right disciplinary authority, how to organize your complaint and evidence, what happens during investigation, what range of sanctions is available, and how to protect your own interests during the process. We also cover the process's significant limitations — and what alternatives exist when bar discipline is not enough.",
    keywords: ["how to file bar complaint", "file complaint against lawyer", "attorney discipline complaint guide", "bar complaint process", "report attorney misconduct"],
  },
  {
    slug: "attorney-discipline-statistics",
    title: "Attorney Discipline by the Numbers: Data, Trends, and System Failures",
    description: "Data and trends in attorney discipline across the United States — complaint volumes, disposition rates, sanction patterns, and what the numbers reveal about a system that protects lawyers more than clients.",
    intro: "The American attorney discipline system processes hundreds of thousands of complaints each year — and dismisses the vast majority without any public sanction. State bar disciplinary authorities and state supreme courts publish annual reports that reveal the system's disposition patterns: intake numbers, investigation rates, formal charge rates, and the distribution of sanctions from private admonition to disbarment. The Ethics Reporter analyzes this data to understand not just individual cases but systemic patterns: which types of misconduct most commonly result in discipline, how discipline rates vary across states, and whether the system's outcomes bear any relationship to the rate at which attorneys actually commit misconduct. The numbers tell a story that the profession prefers not to discuss publicly.",
    keywords: ["attorney discipline statistics", "bar complaint data", "attorney discipline rates", "how many attorneys disbarred", "bar complaint dismissal rate"],
  },
  {
    slug: "real-estate-attorney-ethics",
    title: "Real Estate Attorney Ethics: Conflicts, Dual Representation, and Client Harm",
    description: "Ethics violations in real estate law practice — dual representation conflicts, undisclosed relationships with title companies and developers, and the clients left exposed.",
    intro: "Real estate transactions are among the most significant financial events in most people's lives, and the attorneys who guide them through those transactions occupy positions of extraordinary trust. That trust is frequently abused. Real estate attorneys who represent both buyer and seller without adequate disclosure create inherent conflicts of interest. Attorneys with undisclosed financial relationships to title companies, mortgage brokers, or developers steer clients toward products and services that benefit the attorney rather than the client. The Ethics Reporter investigates real estate attorney ethics violations across the country, examining the cases where the lawyer hired to protect a client's interests in a property transaction was in fact working against those interests.",
    keywords: ["real estate attorney ethics", "dual representation real estate lawyer", "attorney conflict of interest real estate", "real estate lawyer misconduct", "real estate attorney discipline"],
  },
  {
    slug: "immigration-attorney-misconduct",
    title: "Immigration Attorney Misconduct: Fraud, Incompetence, and Vulnerable Clients",
    description: "Immigration attorney fraud and misconduct — the lawyers who steal from asylum seekers, file fake petitions, abandon clients mid-case, and exploit the most vulnerable people in the legal system.",
    intro: "Immigration law is one of the areas of legal practice most plagued by attorney misconduct, for a predictable reason: immigration clients are among the most vulnerable people who interact with the legal system. They may not speak English, may not understand American legal procedures, may face deportation or family separation if their cases fail, and may have limited ability to monitor their attorney's work or seek other counsel. Immigration attorneys who steal client funds, file fraudulent petitions, promise outcomes they cannot deliver, or simply abandon clients mid-case cause devastating, sometimes irreversible harm. The Ethics Reporter investigates immigration attorney misconduct with particular attention to cases involving asylum seekers, visa applicants, and families facing removal.",
    keywords: ["immigration attorney misconduct", "immigration lawyer fraud", "asylum attorney fraud", "immigration attorney discipline", "immigration lawyer steal money"],
  },
  {
    slug: "personal-injury-attorney-ethics",
    title: "Personal Injury Attorney Ethics: Advertising, Fees, and the Ambulance Chaser Problem",
    description: "Ethics violations in personal injury practice — improper solicitation, excessive fees, settlement manipulation, and the attorneys who exploit accident victims.",
    intro: "Personal injury law sits at the intersection of legitimate advocacy and predatory marketing. The contingency fee model — where the attorney collects a percentage of any recovery — creates incentives that can work against clients: attorneys motivated to settle quickly for less than a case is worth, to take cases they cannot properly prosecute, or to charge excessive fees that consume most of the client's recovery. Coupled with aggressive advertising that sometimes crosses into deceptive marketing and prohibited direct solicitation of accident victims, personal injury practice produces a disproportionate share of attorney discipline cases. The Ethics Reporter examines ethical violations in personal injury practice, including excessive fees, inadequate representation, improper solicitation, and the manipulation of settlements.",
    keywords: ["personal injury attorney ethics", "ambulance chaser lawyer", "personal injury attorney fee ethics", "lawyer solicitation ethics", "personal injury attorney discipline"],
  },
  {
    slug: "criminal-defense-attorney-misconduct",
    title: "Criminal Defense Attorney Misconduct: When Defenders Betray Their Clients",
    description: "Misconduct by criminal defense attorneys — lawyers who steal from clients, fail to investigate, miss deadlines, and betray the people whose liberty depends on them.",
    intro: "The criminal defense attorney occupies one of the most important roles in the justice system: standing between the state and an individual whose liberty, reputation, and sometimes life is at stake. The stakes make betrayal of this role particularly devastating. Criminal defense attorneys who fail to investigate their clients' cases, who miss filing deadlines, who negotiate pleas without informing clients of the consequences, who steal from clients facing incarceration, or who simply abandon complex matters mid-representation cause harms that can be genuinely irreversible. The Ethics Reporter investigates criminal defense attorney misconduct with attention to the cases where attorney failures contributed to unjust outcomes — and what the discipline system did, or failed to do, in response.",
    keywords: ["criminal defense attorney misconduct", "defense lawyer ethics violation", "ineffective assistance of counsel", "criminal defense lawyer discipline", "attorney abandonment criminal case"],
  },
  {
    slug: "attorney-false-credentials",
    title: "Attorney False Credentials: Fake Experience, Fabricated Honors, and Resume Fraud",
    description: "Attorneys who falsely claim years of experience they do not have, honors they were not awarded, and credentials that do not exist — and what it means for the clients who rely on those claims.",
    intro: "An attorney's claimed credentials — years of experience, notable cases handled, awards received, certifications earned — are among the most important factors prospective clients consider when choosing representation. They are also among the easiest things to falsify. Attorneys inflate years of experience, claim board certifications that do not exist or were not earned, list honors and recognitions that cannot be verified, and describe prior employment in terms that misrepresent their actual role and responsibility. The Ethics Reporter investigates attorney false credential claims, focusing on cases where inflated credentials led clients to make decisions they would not have made with accurate information — and on the discipline system's response to credential fraud.",
    keywords: ["attorney false credentials", "lawyer fake experience claim", "attorney credential fraud", "misleading attorney credentials", "lawyer resume fraud"],
  },
  {
    slug: "law-firm-marketing-ethics",
    title: "Law Firm Marketing Ethics: SEO Manipulation, Fake Reviews, and Deceptive Tactics",
    description: "The dark side of law firm digital marketing — manufactured reviews, misleading SEO practices, fake case results, and other tactics that violate attorney advertising rules.",
    intro: "The digital marketing industry for law firms operates in a largely unregulated space where attorneys pay firms to manufacture the appearance of success, prominence, and client satisfaction. Fake Google reviews, purchased ratings on legal directories, fabricated case results, misleading 'best lawyer' designations that require nothing more than paying a fee — these practices are endemic, and they help prospective clients make decisions based on false information. The Ethics Reporter investigates law firm marketing practices that cross from aggressive promotion into ethical violation, examining the advertising rules that apply and the enforcement mechanisms that largely fail to address digital marketing misconduct.",
    keywords: ["law firm marketing ethics", "attorney fake reviews", "lawyer SEO manipulation", "attorney advertising digital", "law firm deceptive marketing"],
  },
  {
    slug: "client-abandonment",
    title: "Attorney Client Abandonment: When Lawyers Walk Away Mid-Case",
    description: "Attorneys who abandon clients mid-representation without proper notice, without returning files, and without ensuring continuity of legal protection.",
    intro: "An attorney's obligation to a client does not end when the attorney decides the representation is inconvenient. Rule 1.16 of the Rules of Professional Conduct governs the withdrawal of representation and imposes strict requirements: adequate notice, return of client files, refund of unearned fees, and steps to protect the client's interests during the transition. Yet attorneys abandon clients routinely — sometimes without notice, often without returning files, and frequently in the middle of proceedings where the client cannot afford to hire new counsel. Client abandonment is particularly devastating in criminal cases, where deadlines and appearances cannot wait, and in immigration matters, where a missed filing can mean deportation. This topic covers abandonment cases across the country and the discipline that too often comes too late.",
    keywords: ["attorney client abandonment", "lawyer abandonment ethics", "attorney withdraw from case", "Rule 1.16 attorney withdrawal", "lawyer quit case without notice"],
  },
  {
    slug: "attorney-communication-failures",
    title: "Attorney Communication Failures: The Lawyers Who Won't Return Your Call",
    description: "Rule 1.4 violations — attorneys who fail to communicate with clients, ignore inquiries, and leave clients in the dark about the status of their own legal matters.",
    intro: "Rule 1.4 of the Rules of Professional Conduct requires attorneys to keep clients reasonably informed about the status of their matters, to promptly comply with reasonable requests for information, and to explain developments in a way that allows clients to make informed decisions about their representation. Violations of Rule 1.4 — the communication rule — constitute one of the most common bases for bar complaints in every state. Attorneys who do not return phone calls, fail to inform clients of case developments, neglect to transmit settlement offers, or simply disappear from a matter without explanation are violating a fundamental professional obligation. This topic covers attorney communication failures across the country, with a focus on cases where the failure to communicate caused real harm.",
    keywords: ["attorney communication failures", "Rule 1.4 attorney", "lawyer won't return calls", "attorney client communication ethics", "attorney communication discipline"],
  },
  {
    slug: "contingency-fee-ethics",
    title: "Contingency Fee Ethics: When Attorney Compensation Conflicts with Client Interests",
    description: "The ethics of contingency fee arrangements — when fee structures align attorney and client interests, and when they create conflicts that harm the clients they are supposed to serve.",
    intro: "The contingency fee arrangement — where an attorney agrees to handle a case for a percentage of the recovery, charging no fee if there is no recovery — is one of the primary mechanisms by which people who cannot afford hourly legal fees gain access to the legal system. Properly structured and ethically managed, contingency arrangements create genuine alignment between attorney and client. But they also create dangerous incentives: pressure to settle cases quickly for less than their value, motivation to take cases the attorney cannot properly prosecute, and the potential for fee arrangements that consume so much of the client's recovery that the theoretical access to justice becomes a practical exploitation. This topic examines contingency fee ethics across the country, including cases where fee arrangements crossed the line.",
    keywords: ["contingency fee ethics", "attorney contingency fee misconduct", "lawyer percentage fee ethics", "contingency fee excessive", "attorney fee ethics"],
  },
  {
    slug: "pro-se-litigant-exploitation",
    title: "Exploiting the Self-Represented: How Attorneys Prey on Pro Se Litigants",
    description: "How attorneys and the legal system exploit self-represented litigants — from opposing counsel who take unfair advantage to judges who tolerate procedural abuse of unrepresented parties.",
    intro: "Self-represented litigants — pro se parties who navigate the legal system without an attorney — are among the most vulnerable participants in any court proceeding. They typically do not know procedural rules, do not understand how to preserve issues for appeal, may not recognize when opposing counsel is taking advantage of their inexperience, and often lack the resources to retain counsel even when the stakes are high. The Ethics Reporter examines how attorneys and courts treat self-represented litigants, including cases where opposing counsel took procedural advantages that violated the spirit of fair play, where courts failed to provide basic procedural information to unrepresented parties, and where the judicial system's complexity effectively denied justice to people who could not afford lawyers.",
    keywords: ["pro se litigant exploitation", "self-represented litigant attorney ethics", "pro se party attorney misconduct", "exploiting unrepresented party", "pro se attorney fairness"],
  },
  {
    slug: "new-york-judiciary-law-470",
    title: "New York Judiciary Law §470: The Office Requirement Every New York Attorney Must Meet",
    description: "New York Judiciary Law §470 requires attorneys admitted in New York to maintain a physical office in the state. We explain what the law requires, how it has been interpreted, and our investigation of attorneys who may be violating it.",
    intro: "New York Judiciary Law §470 states that any person admitted to practice law in this state who is not a resident of New York may not practice law in New York unless they maintain 'an office for the transaction of law business within the state.' The New York Court of Appeals has interpreted this requirement to mean a genuine, physical law office — not a virtual mailbox, not a coworking membership, not a shared desk arrangement. Our investigation of Ernestas Pravilionis and EPRA Legal found that all three of the firm's listed New York office addresses appear to be virtual services, not physical law offices. This topic covers §470's history, the case law interpreting it, the practical consequences of violation, and what the New York grievance committees have said about the requirement.",
    keywords: ["New York Judiciary Law 470", "NY Judiciary Law 470 attorney", "attorney physical office New York requirement", "virtual office attorney New York law", "Judiciary Law 470 violation"],
  },
];
