export interface CitadelStateData {
  name: string;
  slug: string;
  abbr: string;
  ag: string;
  securitiesRegulator: string;
  securitiesRegulatorFull: string;
  population: number; // approx
  retailInvestors: string; // narrative estimate
  griffinDonations: GriffinDonation[];
  griffinTotalEstimate: string;
  keyRecipients: string;
  majorFinancialCities: string[];
  financialHub: string;
  stateSpecificHarm: string;
  regulatoryAction: string;
  agContactUrl: string;
  securitiesUrl: string;
}

export interface GriffinDonation {
  recipient: string;
  amount: string;
  year: string;
  office: string;
  note?: string;
}

export const citadelStatesData: CitadelStateData[] = [
  {
    name: "Alabama",
    slug: "alabama",
    abbr: "AL",
    ag: "Steve Marshall",
    securitiesRegulator: "Alabama Securities Commission",
    securitiesRegulatorFull: "Alabama Securities Commission",
    population: 5024279,
    retailInvestors: "an estimated 800,000 Alabama retail investors",
    griffinDonations: [
      { recipient: "Tommy Tuberville (R-AL Senate)", amount: "$10,000", year: "2020", office: "U.S. Senate" },
      { recipient: "Republican Senate Leadership Fund", amount: "$2,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "more than $2 million in identifiable political donations affecting Alabama's federal delegation",
    keyRecipients: "Senator Tommy Tuberville and Republican Senate super PACs that fund Alabama candidates",
    majorFinancialCities: ["Birmingham", "Huntsville", "Montgomery", "Mobile"],
    financialHub: "Birmingham",
    stateSpecificHarm: "Alabama retail investors—many of whom rely on discount brokers for retirement savings—have their orders routed through Citadel Securities without disclosure. The spread capture on Alabama-originating orders is estimated in the millions annually.",
    regulatoryAction: "Alabama Attorney General Steve Marshall could join a multistate investigation into payment for order flow practices, and the Alabama Securities Commission has authority under the Alabama Securities Act of 1959 to investigate broker-dealer conflicts of interest affecting Alabama residents.",
    agContactUrl: "https://www.alabamaag.gov",
    securitiesUrl: "https://www.asc.alabama.gov",
  },
  {
    name: "Alaska",
    slug: "alaska",
    abbr: "AK",
    ag: "Treg Taylor",
    securitiesRegulator: "Alaska Division of Banking and Securities",
    securitiesRegulatorFull: "Alaska Division of Banking and Securities",
    population: 733391,
    retailInvestors: "an estimated 120,000 Alaska retail investors",
    griffinDonations: [
      { recipient: "Republican Governors Association", amount: "$500,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "identifiable donations to national Republican entities that fund Alaska Republicans",
    keyRecipients: "the Republican Governors Association, which has funded Alaska gubernatorial candidates",
    majorFinancialCities: ["Anchorage", "Fairbanks", "Juneau"],
    financialHub: "Anchorage",
    stateSpecificHarm: "Alaska's isolated retail investor population—many managing permanent fund dividends and retirement accounts—depends on online brokers routed through Citadel Securities. The opacity of PFOF arrangements means Alaska investors cannot assess the true cost of their trades.",
    regulatoryAction: "Alaska Attorney General Treg Taylor and the Alaska Division of Banking and Securities have authority to investigate broker-dealer practices affecting Alaska residents under AS 45.55. A referral to NASAA for coordinated multistate action would amplify Alaska's leverage.",
    agContactUrl: "https://law.alaska.gov",
    securitiesUrl: "https://www.commerce.alaska.gov/web/dbs",
  },
  {
    name: "Arizona",
    slug: "arizona",
    abbr: "AZ",
    ag: "Kris Mayes",
    securitiesRegulator: "Arizona Corporation Commission Securities Division",
    securitiesRegulatorFull: "Arizona Corporation Commission, Securities Division",
    population: 7151502,
    retailInvestors: "an estimated 1.3 million Arizona retail investors",
    griffinDonations: [
      { recipient: "Blake Masters (R-AZ Senate)", amount: "$500,000", year: "2022", office: "U.S. Senate" },
      { recipient: "Republican Senate Leadership Fund", amount: "$2,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "more than $2.5 million to Arizona-linked political recipients",
    keyRecipients: "Blake Masters' Senate campaign and the Republican Senate Leadership Fund that targeted Arizona",
    majorFinancialCities: ["Phoenix", "Scottsdale", "Tempe", "Tucson"],
    financialHub: "Phoenix",
    stateSpecificHarm: "Arizona has a large retiree population in the Sun Belt—many of whom are active retail investors managing IRA and 401(k) assets through discount brokers. PFOF practices mean these investors subsidize Citadel Securities' profits on every trade.",
    regulatoryAction: "Arizona Attorney General Kris Mayes has shown willingness to pursue corporate accountability and could lead or join a multistate PFOF investigation. The Arizona Corporation Commission's Securities Division has independent authority to examine broker-dealer conflicts under A.R.S. §44-1961.",
    agContactUrl: "https://www.azag.gov",
    securitiesUrl: "https://www.azcc.gov/securities",
  },
  {
    name: "Arkansas",
    slug: "arkansas",
    abbr: "AR",
    ag: "Tim Griffin",
    securitiesRegulator: "Arkansas Securities Department",
    securitiesRegulatorFull: "Arkansas Securities Department",
    population: 3011524,
    retailInvestors: "an estimated 500,000 Arkansas retail investors",
    griffinDonations: [
      { recipient: "Tom Cotton (R-AR Senate)", amount: "$10,000", year: "2020", office: "U.S. Senate" },
      { recipient: "Republican Senate Leadership Fund", amount: "$2,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "millions through national Republican super PACs that support Arkansas's federal delegation",
    keyRecipients: "Senator Tom Cotton and national Republican committees that fund Arkansas candidates",
    majorFinancialCities: ["Little Rock", "Fayetteville", "Fort Smith"],
    financialHub: "Little Rock",
    stateSpecificHarm: "Arkansas retail investors, many of them rural and reliant on mobile trading apps, face undisclosed costs embedded in Citadel's market-making spread. The lack of best-execution enforcement means Arkansas investors have no practical recourse.",
    regulatoryAction: "Arkansas Attorney General Tim Griffin and the Arkansas Securities Department have jurisdiction under the Arkansas Securities Act (A.C.A. §23-42-101 et seq.) to investigate broker-dealer practices affecting state residents.",
    agContactUrl: "https://arkansasag.gov",
    securitiesUrl: "https://securities.arkansas.gov",
  },
  {
    name: "California",
    slug: "california",
    abbr: "CA",
    ag: "Rob Bonta",
    securitiesRegulator: "California Department of Financial Protection and Innovation",
    securitiesRegulatorFull: "California Department of Financial Protection and Innovation (DFPI)",
    population: 39538223,
    retailInvestors: "an estimated 8 million California retail investors — the largest single-state population of retail traders in the country",
    griffinDonations: [
      { recipient: "Preserve America PAC (DeSantis)", amount: "$50,000,000", year: "2022", office: "Presidential Super PAC", note: "Largest single donation in Florida political history" },
      { recipient: "Richard Grenell ballot initiative", amount: "$100,000", year: "2022", office: "California initiative" },
    ],
    griffinTotalEstimate: "at least $50 million nationally in 2022 alone, with California-proximate recipients benefiting from Griffin's national Republican investment",
    keyRecipients: "national Republican super PACs with California operations and select California initiatives",
    majorFinancialCities: ["San Francisco", "Los Angeles", "San Jose", "San Diego", "Sacramento"],
    financialHub: "San Francisco",
    stateSpecificHarm: "California retail investors are the most heavily affected in the nation by PFOF arrangements. Robinhood, the poster child for PFOF, has millions of California users—all routing orders to Citadel Securities. The estimated annual transfer of value from California retail investors to Citadel through spread capture runs into the hundreds of millions.",
    regulatoryAction: "California Attorney General Rob Bonta and the DFPI are positioned to lead the nation's response to PFOF abuses. California's Unfair Competition Law (Business & Professions Code §17200) provides a powerful tool to investigate and enjoin deceptive payment-for-order-flow arrangements that harm California consumers.",
    agContactUrl: "https://oag.ca.gov",
    securitiesUrl: "https://dfpi.ca.gov",
  },
  {
    name: "Colorado",
    slug: "colorado",
    abbr: "CO",
    ag: "Phil Weiser",
    securitiesRegulator: "Colorado Division of Securities",
    securitiesRegulatorFull: "Colorado Division of Securities, Department of Regulatory Agencies",
    population: 5773714,
    retailInvestors: "an estimated 1 million Colorado retail investors",
    griffinDonations: [
      { recipient: "Republican Governors Association", amount: "$500,000", year: "2022", office: "Federal Super PAC" },
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "millions through national Republican committees that target competitive Colorado races",
    keyRecipients: "national Republican Senate and gubernatorial committees that fund Colorado candidates",
    majorFinancialCities: ["Denver", "Boulder", "Colorado Springs", "Fort Collins"],
    financialHub: "Denver",
    stateSpecificHarm: "Colorado has a highly educated, tech-savvy investor population with significant 401(k) and IRA assets managed through discount brokers. PFOF practices affect this sophisticated but underserved investor community.",
    regulatoryAction: "Colorado Attorney General Phil Weiser has been an aggressive consumer-protection advocate and could pursue Citadel-related PFOF claims under the Colorado Consumer Protection Act (C.R.S. §6-1-101 et seq.).",
    agContactUrl: "https://coag.gov",
    securitiesUrl: "https://www.sos.state.co.us/securities",
  },
  {
    name: "Connecticut",
    slug: "connecticut",
    abbr: "CT",
    ag: "William Tong",
    securitiesRegulator: "Connecticut Department of Banking, Securities and Business Investments Division",
    securitiesRegulatorFull: "Connecticut Department of Banking, Securities and Business Investments Division",
    population: 3605944,
    retailInvestors: "an estimated 700,000 Connecticut retail investors — with disproportionate wealth and trading activity given the state's proximity to Wall Street",
    griffinDonations: [
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "millions through national Republican organizations that compete for Connecticut's federal seats",
    keyRecipients: "national Republican Senate committees",
    majorFinancialCities: ["Greenwich", "Stamford", "Hartford", "Westport"],
    financialHub: "Greenwich/Stamford",
    stateSpecificHarm: "Connecticut is home to numerous hedge funds and sophisticated investors in Greenwich and Stamford — but retail investors statewide use the same discount brokers and are subject to the same PFOF practices. The irony is that Connecticut's wealthy financial professionals understand PFOF's harm while ordinary residents are unprotected.",
    regulatoryAction: "Connecticut Attorney General William Tong has been active in financial consumer protection and could pursue PFOF claims under the Connecticut Unfair Trade Practices Act (CUTPA). The Connecticut Banking Department has securities enforcement authority under C.G.S. §36b-2.",
    agContactUrl: "https://portal.ct.gov/AG",
    securitiesUrl: "https://portal.ct.gov/DOB",
  },
  {
    name: "Delaware",
    slug: "delaware",
    abbr: "DE",
    ag: "Kathy Jennings",
    securitiesRegulator: "Delaware Division of Securities",
    securitiesRegulatorFull: "Delaware Division of Securities, Department of Justice",
    population: 989948,
    retailInvestors: "an estimated 180,000 Delaware retail investors",
    griffinDonations: [
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "millions through national Republican organizations",
    keyRecipients: "the Republican National Committee and national Republican organizations",
    majorFinancialCities: ["Wilmington", "Dover", "Newark"],
    financialHub: "Wilmington",
    stateSpecificHarm: "Delaware is the legal home of most American corporations—including many financial firms. Delaware retail investors may have unique legal standing under Delaware corporate law to challenge broker-dealer conflicts of interest given the state's sophisticated chancery court system.",
    regulatoryAction: "Delaware Attorney General Kathy Jennings, whose office already incorporates securities divisions, could leverage Delaware's unique position as the corporate home of Citadel's legal entities to demand greater accountability.",
    agContactUrl: "https://ago.delaware.gov",
    securitiesUrl: "https://securities.delaware.gov",
  },
  {
    name: "Florida",
    slug: "florida",
    abbr: "FL",
    ag: "James Uthmeier",
    securitiesRegulator: "Florida Office of Financial Regulation",
    securitiesRegulatorFull: "Florida Office of Financial Regulation, Division of Securities",
    population: 21538187,
    retailInvestors: "an estimated 4.5 million Florida retail investors — the second-largest state retail investor population",
    griffinDonations: [
      { recipient: "Preserve America PAC (Ron DeSantis)", amount: "$50,000,000", year: "2022", office: "Florida Governor / Presidential Super PAC", note: "Largest single donation in Florida political history" },
      { recipient: "Ron DeSantis reelection campaign", amount: "$1,000,000", year: "2022", office: "Florida Governor" },
      { recipient: "Republican Governors Association", amount: "$5,000,000", year: "2022", office: "Federal Super PAC" },
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "more than $57 million directly tied to Florida political figures in the 2022 cycle alone — an extraordinary concentration of political spending",
    keyRecipients: "Governor Ron DeSantis, whose Preserve America PAC received $50 million from Griffin — the largest single donation in Florida political history — as well as Republican statewide committees",
    majorFinancialCities: ["Miami", "Tampa", "Orlando", "Jacksonville", "Fort Lauderdale", "Boca Raton"],
    financialHub: "Miami",
    stateSpecificHarm: "Florida is now Kenneth Griffin's home state after he relocated Citadel's headquarters to Miami. Florida retail investors — from Panhandle retirees to Miami day traders — route orders through Citadel Securities, generating enormous profits for a company whose CEO has spent $57 million on Florida political figures. The conflict of interest between Griffin's political giving and the absence of Florida regulatory action is acute.",
    regulatoryAction: "Florida's Office of Financial Regulation has jurisdiction to investigate PFOF practices under Florida securities law (Chapter 517, F.S.). Given Griffin's $50 million donation to DeSantis, there are serious questions about whether Florida regulators can act independently — making federal and multistate action all the more critical for Florida investors.",
    agContactUrl: "https://myfloridalegal.com",
    securitiesUrl: "https://flofr.gov",
  },
  {
    name: "Georgia",
    slug: "georgia",
    abbr: "GA",
    ag: "Chris Carr",
    securitiesRegulator: "Georgia Secretary of State, Securities Division",
    securitiesRegulatorFull: "Georgia Secretary of State, Securities and Charities Division",
    population: 10711908,
    retailInvestors: "an estimated 2 million Georgia retail investors",
    griffinDonations: [
      { recipient: "Brian Kemp (R-GA Governor)", amount: "$250,000", year: "2022", office: "Georgia Governor" },
      { recipient: "Republican Governors Association", amount: "$5,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "more than $5 million tied to Georgia's political establishment",
    keyRecipients: "Governor Brian Kemp and the Republican Governors Association, which heavily invested in Georgia's 2022 governor's race",
    majorFinancialCities: ["Atlanta", "Savannah", "Augusta", "Columbus"],
    financialHub: "Atlanta",
    stateSpecificHarm: "Atlanta's growing tech and financial services sector has created a large population of retail investors. Georgia retail investors' orders are routed to Citadel Securities without their knowledge, generating revenues for a company whose CEO has donated directly to the governor overseeing state financial regulators.",
    regulatoryAction: "Georgia Attorney General Chris Carr and the Georgia Secretary of State's Securities Division have authority under the Georgia Securities Act (O.C.G.A. §10-5-1 et seq.) to investigate broker-dealer conflicts affecting Georgia investors.",
    agContactUrl: "https://law.georgia.gov",
    securitiesUrl: "https://sos.ga.gov/securities",
  },
  {
    name: "Hawaii",
    slug: "hawaii",
    abbr: "HI",
    ag: "Anne Lopez",
    securitiesRegulator: "Hawaii Department of Commerce and Consumer Affairs, Securities Enforcement Branch",
    securitiesRegulatorFull: "Hawaii Division of Financial Institutions, Securities Enforcement Branch",
    population: 1455271,
    retailInvestors: "an estimated 250,000 Hawaii retail investors",
    griffinDonations: [
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations",
    keyRecipients: "national Republican organizations",
    majorFinancialCities: ["Honolulu", "Hilo", "Kailua"],
    financialHub: "Honolulu",
    stateSpecificHarm: "Hawaii retail investors face the same PFOF harms as mainland investors but with additional disadvantages: higher cost of financial services due to geographic isolation, and limited access to investor advocacy resources.",
    regulatoryAction: "Hawaii Attorney General Anne Lopez and the Hawaii Securities Enforcement Branch have jurisdiction under the Hawaii Uniform Securities Act (H.R.S. Chapter 485A) to investigate broker-dealer practices affecting Hawaii residents.",
    agContactUrl: "https://ag.hawaii.gov",
    securitiesUrl: "https://cca.hawaii.gov/sec",
  },
  {
    name: "Idaho",
    slug: "idaho",
    abbr: "ID",
    ag: "Raúl Labrador",
    securitiesRegulator: "Idaho Department of Finance",
    securitiesRegulatorFull: "Idaho Department of Finance, Securities Bureau",
    population: 1839106,
    retailInvestors: "an estimated 310,000 Idaho retail investors",
    griffinDonations: [
      { recipient: "Republican Governors Association", amount: "$500,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations funding Idaho Republican candidates",
    keyRecipients: "the Republican Governors Association, which has invested in Idaho's gubernatorial races",
    majorFinancialCities: ["Boise", "Nampa", "Meridian", "Idaho Falls"],
    financialHub: "Boise",
    stateSpecificHarm: "Idaho's rapidly growing population — driven by migration from California and other high-cost states — includes many retail investors who have brought assets to Idaho brokerages and discount trading platforms, all subject to PFOF practices.",
    regulatoryAction: "Idaho Attorney General Raúl Labrador and the Idaho Department of Finance have authority under the Idaho Securities Act (I.C. §30-14-101 et seq.) to investigate broker-dealer conflicts affecting Idaho investors.",
    agContactUrl: "https://www.ag.idaho.gov",
    securitiesUrl: "https://finance.idaho.gov",
  },
  {
    name: "Illinois",
    slug: "illinois",
    abbr: "IL",
    ag: "Kwame Raoul",
    securitiesRegulator: "Illinois Secretary of State, Securities Department",
    securitiesRegulatorFull: "Illinois Secretary of State, Securities Department",
    population: 12812508,
    retailInvestors: "an estimated 2.8 million Illinois retail investors — the state with the most direct connection to Citadel's headquarters",
    griffinDonations: [
      { recipient: "Bruce Rauner (R-IL Governor)", amount: "$27,600,000", year: "2014", office: "Illinois Governor", note: "Historic amount — enabled Rauner's upset of incumbent Pat Quinn" },
      { recipient: "Bruce Rauner (R-IL Governor)", amount: "$20,000,000+", year: "2018", office: "Illinois Governor re-election" },
      { recipient: "Illinois Republican Party", amount: "$2,000,000+", year: "2018-2022", office: "State party" },
      { recipient: "Preserve America PAC (DeSantis)", amount: "$50,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "more than $100 million in Illinois-linked and national political donations over the past decade — making Griffin one of the most consequential political donors in Illinois history",
    keyRecipients: "Governor Bruce Rauner (to whom Griffin gave $27.6 million in 2014, the largest single donation in Illinois history at the time), the Illinois Republican Party, and national super PACs",
    majorFinancialCities: ["Chicago", "Naperville", "Rockford", "Elgin", "Peoria"],
    financialHub: "Chicago",
    stateSpecificHarm: "Illinois is Citadel Securities' historical home. Every Illinois retail investor's trade at a discount broker likely flows through a company that has spent tens of millions shaping Illinois politics. The regulatory capture concern is most acute here: Illinois politicians who received Griffin's money have had little incentive to scrutinize Citadel's practices.",
    regulatoryAction: "Illinois Attorney General Kwame Raoul could investigate PFOF practices under the Illinois Consumer Fraud and Deceptive Business Practices Act (815 ILCS 505/) and the Illinois Securities Law of 1953. The Attorney General's office has historically been aggressive on financial consumer protection — the question is whether Griffin's political influence has created a chilling effect.",
    agContactUrl: "https://illinoisattorneygeneral.gov",
    securitiesUrl: "https://www.ilsos.gov/departments/securities",
  },
  {
    name: "Indiana",
    slug: "indiana",
    abbr: "IN",
    ag: "Todd Rokita",
    securitiesRegulator: "Indiana Secretary of State, Securities Division",
    securitiesRegulatorFull: "Indiana Secretary of State, Securities Division",
    population: 6785528,
    retailInvestors: "an estimated 1.2 million Indiana retail investors",
    griffinDonations: [
      { recipient: "Mike Pence reelection fund", amount: "$100,000", year: "2016", office: "Indiana Governor" },
      { recipient: "Republican Governors Association", amount: "$500,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "millions through national Republican organizations, including contributions tied to Indiana's leadership",
    keyRecipients: "then-Governor Mike Pence and national Republican committees",
    majorFinancialCities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend"],
    financialHub: "Indianapolis",
    stateSpecificHarm: "Indiana's industrial heartland has a large working-class retail investor base with significant exposure to 401(k) investments routed through PFOF-dependent brokers.",
    regulatoryAction: "Indiana Attorney General Todd Rokita and the Indiana Securities Division have jurisdiction under the Indiana Uniform Securities Act (I.C. 23-19-1-1 et seq.) to investigate market maker conflicts affecting Indiana residents.",
    agContactUrl: "https://www.in.gov/attorneygeneral",
    securitiesUrl: "https://www.in.gov/sos/securities",
  },
  {
    name: "Iowa",
    slug: "iowa",
    abbr: "IA",
    ag: "Brenna Bird",
    securitiesRegulator: "Iowa Insurance Division, Securities Bureau",
    securitiesRegulatorFull: "Iowa Insurance Division, Securities and Regulated Industries Bureau",
    population: 3190369,
    retailInvestors: "an estimated 550,000 Iowa retail investors",
    griffinDonations: [
      { recipient: "Joni Ernst (R-IA Senate)", amount: "$10,000", year: "2020", office: "U.S. Senate" },
      { recipient: "Chuck Grassley (R-IA Senate)", amount: "$10,000", year: "2022", office: "U.S. Senate" },
    ],
    griffinTotalEstimate: "contributions to Iowa's senior federal delegation and national Republican organizations",
    keyRecipients: "Senators Joni Ernst and Chuck Grassley, both of whom sit on committees with financial regulatory jurisdiction",
    majorFinancialCities: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City"],
    financialHub: "Des Moines",
    stateSpecificHarm: "Iowa's agricultural economy means many retail investors are farming families managing savings and retirement accounts through discount brokers — all subject to undisclosed PFOF arrangements.",
    regulatoryAction: "Iowa Attorney General Brenna Bird and the Iowa Insurance Division's Securities Bureau have authority under the Iowa Uniform Securities Act (Iowa Code Chapter 502) to investigate broker-dealer practices.",
    agContactUrl: "https://www.iowaattorneygeneral.gov",
    securitiesUrl: "https://iid.iowa.gov/securities",
  },
  {
    name: "Kansas",
    slug: "kansas",
    abbr: "KS",
    ag: "Kris Kobach",
    securitiesRegulator: "Kansas Securities Commissioner",
    securitiesRegulatorFull: "Kansas Office of the Securities Commissioner",
    population: 2937880,
    retailInvestors: "an estimated 500,000 Kansas retail investors",
    griffinDonations: [
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2020", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations",
    keyRecipients: "the National Republican Senatorial Committee and related super PACs",
    majorFinancialCities: ["Wichita", "Overland Park", "Kansas City", "Topeka"],
    financialHub: "Overland Park",
    stateSpecificHarm: "Kansas retail investors have limited access to financial advocacy resources and depend primarily on national discount brokers, all of which route order flow to Citadel Securities.",
    regulatoryAction: "Kansas Attorney General Kris Kobach and the Kansas Securities Commissioner have jurisdiction under the Kansas Securities Act (K.S.A. 17-12a101 et seq.) to investigate market maker conflicts.",
    agContactUrl: "https://ag.ks.gov",
    securitiesUrl: "https://www.ksc.ks.gov",
  },
  {
    name: "Kentucky",
    slug: "kentucky",
    abbr: "KY",
    ag: "Russell Coleman",
    securitiesRegulator: "Kentucky Department of Financial Institutions",
    securitiesRegulatorFull: "Kentucky Department of Financial Institutions, Division of Securities",
    population: 4505836,
    retailInvestors: "an estimated 750,000 Kentucky retail investors",
    griffinDonations: [
      { recipient: "Mitch McConnell Leadership PAC", amount: "$1,000,000", year: "2020", office: "Senate Majority Leader Super PAC" },
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "more than $2 million to Kentucky-linked political figures and organizations",
    keyRecipients: "Senator Mitch McConnell's leadership PAC and the NRSC — McConnell was Senate Majority Leader during the period of PFOF controversy and took no action on market structure reform",
    majorFinancialCities: ["Louisville", "Lexington", "Bowling Green", "Frankfort"],
    financialHub: "Louisville",
    stateSpecificHarm: "Kentucky retail investors depend heavily on employer-sponsored plans and discount brokers. The state's coal and manufacturing economies have left many workers with IRA accounts subject to PFOF-based order routing.",
    regulatoryAction: "Kentucky Attorney General Russell Coleman and the Kentucky Department of Financial Institutions have authority under the Kentucky Securities Act (KRS Chapter 292) to investigate broker-dealer practices.",
    agContactUrl: "https://ag.ky.gov",
    securitiesUrl: "https://kfi.ky.gov",
  },
  {
    name: "Louisiana",
    slug: "louisiana",
    abbr: "LA",
    ag: "Liz Murrill",
    securitiesRegulator: "Louisiana Office of Financial Institutions",
    securitiesRegulatorFull: "Louisiana Office of Financial Institutions, Securities Division",
    population: 4657757,
    retailInvestors: "an estimated 750,000 Louisiana retail investors",
    griffinDonations: [
      { recipient: "Bill Cassidy (R-LA Senate)", amount: "$25,000", year: "2022", office: "U.S. Senate" },
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "millions through national Republican organizations that fund Louisiana candidates",
    keyRecipients: "Senator Bill Cassidy, a member of the Senate Finance Committee, and national Republican organizations",
    majorFinancialCities: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette"],
    financialHub: "New Orleans",
    stateSpecificHarm: "Louisiana's oil and gas worker population has significant retirement savings managed through PFOF-dependent brokers. Post-Hurricane Katrina recovery investments and insurance payouts have also flowed into retail brokerage accounts.",
    regulatoryAction: "Louisiana Attorney General Liz Murrill and the Louisiana Office of Financial Institutions have authority under Louisiana securities law (R.S. 51:701 et seq.) to investigate market maker conflicts.",
    agContactUrl: "https://www.ag.state.la.us",
    securitiesUrl: "https://www.ofi.la.gov",
  },
  {
    name: "Maine",
    slug: "maine",
    abbr: "ME",
    ag: "Aaron Frey",
    securitiesRegulator: "Maine Office of Securities",
    securitiesRegulatorFull: "Maine Office of Securities, Department of Professional and Financial Regulation",
    population: 1362359,
    retailInvestors: "an estimated 230,000 Maine retail investors",
    griffinDonations: [
      { recipient: "Susan Collins (R-ME Senate)", amount: "$10,000", year: "2020", office: "U.S. Senate" },
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2020", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions to Senator Collins and national Republican organizations",
    keyRecipients: "Senator Susan Collins, a member of the Senate Commerce Committee, and national Republican organizations",
    majorFinancialCities: ["Portland", "Bangor", "Augusta", "Lewiston"],
    financialHub: "Portland",
    stateSpecificHarm: "Maine's large retiree and fishing industry populations include many retail investors managing savings through national discount brokers, all subject to undisclosed PFOF practices.",
    regulatoryAction: "Maine Attorney General Aaron Frey and the Maine Office of Securities have authority under the Maine Uniform Securities Act (32 M.R.S.A. §10101 et seq.) to investigate broker-dealer conflicts.",
    agContactUrl: "https://www.maine.gov/ag",
    securitiesUrl: "https://www.maine.gov/pfr/securities",
  },
  {
    name: "Maryland",
    slug: "maryland",
    abbr: "MD",
    ag: "Anthony Brown",
    securitiesRegulator: "Maryland Office of the Attorney General, Securities Division",
    securitiesRegulatorFull: "Maryland Office of the Attorney General, Securities Division",
    population: 6177224,
    retailInvestors: "an estimated 1.2 million Maryland retail investors — with a highly educated, high-income population near Washington DC",
    griffinDonations: [
      { recipient: "Larry Hogan (R-MD Governor)", amount: "$150,000", year: "2022", office: "Maryland Governor" },
      { recipient: "Republican Governors Association", amount: "$5,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "more than $5 million tied to Maryland's political establishment",
    keyRecipients: "Governor Larry Hogan and the Republican Governors Association that supported his administration",
    majorFinancialCities: ["Baltimore", "Bethesda", "Rockville", "Annapolis", "Silver Spring"],
    financialHub: "Baltimore",
    stateSpecificHarm: "Maryland's proximity to Washington means many federal government employees and contractors rely on discount brokers for retirement savings — all subject to PFOF arrangements that fund a company engaged in extensive political giving.",
    regulatoryAction: "Maryland Attorney General Anthony Brown, whose office directly houses the Securities Division, has both jurisdiction and political motivation to investigate PFOF abuses under the Maryland Securities Act (Corporations and Associations Article, §11-101 et seq.).",
    agContactUrl: "https://www.marylandattorneygeneral.gov",
    securitiesUrl: "https://www.marylandattorneygeneral.gov/Pages/Securities/default.aspx",
  },
  {
    name: "Massachusetts",
    slug: "massachusetts",
    abbr: "MA",
    ag: "Andrea Campbell",
    securitiesRegulator: "Massachusetts Securities Division",
    securitiesRegulatorFull: "Massachusetts Securities Division, Office of the Secretary of the Commonwealth",
    population: 7029917,
    retailInvestors: "an estimated 1.5 million Massachusetts retail investors — in a state with historically aggressive securities enforcement",
    griffinDonations: [
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2020", office: "Federal Super PAC" },
      { recipient: "Congressional Leadership Fund", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "millions through national Republican organizations",
    keyRecipients: "national Republican committees that have targeted Massachusetts congressional seats",
    majorFinancialCities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
    financialHub: "Boston",
    stateSpecificHarm: "Massachusetts has historically been the most aggressive state securities regulator in the country. Secretary of State William Galvin has brought landmark PFOF-related enforcement actions. Massachusetts investors deserve continued robust enforcement as Citadel's practices persist.",
    regulatoryAction: "Massachusetts Secretary of the Commonwealth and Securities Division have already taken enforcement actions related to PFOF and best execution. Attorney General Andrea Campbell could amplify this work under the Massachusetts Consumer Protection Act (M.G.L. c. 93A). Massachusetts should lead the nation in a multistate PFOF investigation.",
    agContactUrl: "https://www.mass.gov/orgs/office-of-the-attorney-general",
    securitiesUrl: "https://www.sec.state.ma.us",
  },
  {
    name: "Michigan",
    slug: "michigan",
    abbr: "MI",
    ag: "Dana Nessel",
    securitiesRegulator: "Michigan Department of Licensing and Regulatory Affairs",
    securitiesRegulatorFull: "Michigan Department of Licensing and Regulatory Affairs, Securities and Audit Division",
    population: 10077331,
    retailInvestors: "an estimated 1.8 million Michigan retail investors",
    griffinDonations: [
      { recipient: "Republican Governors Association", amount: "$5,000,000", year: "2022", office: "Federal Super PAC" },
      { recipient: "Tudor Dixon (R-MI Governor)", amount: "$500,000", year: "2022", office: "Michigan Governor" },
    ],
    griffinTotalEstimate: "more than $5.5 million in contributions tied to Michigan's political establishment",
    keyRecipients: "Michigan gubernatorial candidate Tudor Dixon and the Republican Governors Association",
    majorFinancialCities: ["Detroit", "Grand Rapids", "Lansing", "Ann Arbor", "Flint"],
    financialHub: "Detroit",
    stateSpecificHarm: "Michigan's auto industry workers and retirees hold significant pension and IRA assets routed through discount brokers. PFOF practices extract value from these working-class investors without disclosure.",
    regulatoryAction: "Michigan Attorney General Dana Nessel has been an active consumer protection advocate and could pursue PFOF claims under Michigan securities law (M.C.L. §451.2101 et seq.) and the Michigan Consumer Protection Act.",
    agContactUrl: "https://www.michigan.gov/ag",
    securitiesUrl: "https://www.michigan.gov/lara/bureau-list/corporations-securities-commercial-licensing",
  },
  {
    name: "Minnesota",
    slug: "minnesota",
    abbr: "MN",
    ag: "Keith Ellison",
    securitiesRegulator: "Minnesota Department of Commerce, Securities Division",
    securitiesRegulatorFull: "Minnesota Department of Commerce, Securities Division",
    population: 5706494,
    retailInvestors: "an estimated 1 million Minnesota retail investors",
    griffinDonations: [
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2020", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations that fund Minnesota candidates",
    keyRecipients: "national Republican committees that have invested in competitive Minnesota Senate races",
    majorFinancialCities: ["Minneapolis", "St. Paul", "Rochester", "Duluth", "Bloomington"],
    financialHub: "Minneapolis",
    stateSpecificHarm: "Minnesota has a large financial services sector and significant retail investor population. Minneapolis is home to major financial institutions, and Minnesota investors face the same PFOF-driven conflicts as investors nationwide.",
    regulatoryAction: "Minnesota Attorney General Keith Ellison has been among the most aggressive state AGs on corporate accountability and could lead a multistate PFOF investigation. The Minnesota Department of Commerce has securities enforcement authority under Minn. Stat. §80A.01 et seq.",
    agContactUrl: "https://www.ag.state.mn.us",
    securitiesUrl: "https://mn.gov/commerce/industries/securities",
  },
  {
    name: "Mississippi",
    slug: "mississippi",
    abbr: "MS",
    ag: "Lynn Fitch",
    securitiesRegulator: "Mississippi Secretary of State, Securities Division",
    securitiesRegulatorFull: "Mississippi Secretary of State, Business Services and Securities Division",
    population: 2961279,
    retailInvestors: "an estimated 460,000 Mississippi retail investors",
    griffinDonations: [
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations",
    keyRecipients: "the Republican National Committee and national Republican organizations",
    majorFinancialCities: ["Jackson", "Gulfport", "Southaven", "Hattiesburg"],
    financialHub: "Jackson",
    stateSpecificHarm: "Mississippi retail investors face the compounded disadvantage of lower incomes, higher percentage of savings invested in discount brokers, and no state-level enforcement action on PFOF.",
    regulatoryAction: "Mississippi Attorney General Lynn Fitch and the Mississippi Secretary of State's Securities Division have authority under the Mississippi Securities Act (Miss. Code Ann. §75-71-101 et seq.) to investigate broker-dealer practices.",
    agContactUrl: "https://www.ago.state.ms.us",
    securitiesUrl: "https://www.sos.ms.gov/securities",
  },
  {
    name: "Missouri",
    slug: "missouri",
    abbr: "MO",
    ag: "Andrew Bailey",
    securitiesRegulator: "Missouri Secretary of State, Securities Division",
    securitiesRegulatorFull: "Missouri Secretary of State, Securities Division",
    population: 6154913,
    retailInvestors: "an estimated 1.1 million Missouri retail investors",
    griffinDonations: [
      { recipient: "Eric Greitens (R-MO Governor)", amount: "$50,000", year: "2016", office: "Missouri Governor" },
      { recipient: "Republican Governors Association", amount: "$500,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions to Missouri political figures and national Republican organizations",
    keyRecipients: "former Governor Eric Greitens and the Republican Governors Association",
    majorFinancialCities: ["Kansas City", "St. Louis", "Springfield", "Columbia"],
    financialHub: "Kansas City",
    stateSpecificHarm: "Missouri retail investors in St. Louis and Kansas City financial centers face the same PFOF-driven conflicts as national investors, with limited state regulatory enforcement.",
    regulatoryAction: "Missouri Attorney General Andrew Bailey and the Missouri Securities Division have authority under the Missouri Securities Act of 2003 (RSMo §409.1-101 et seq.) to investigate market maker conflicts.",
    agContactUrl: "https://ago.mo.gov",
    securitiesUrl: "https://www.sos.mo.gov/securities",
  },
  {
    name: "Montana",
    slug: "montana",
    abbr: "MT",
    ag: "Austin Knudsen",
    securitiesRegulator: "Montana Commissioner of Securities and Insurance",
    securitiesRegulatorFull: "Montana Commissioner of Securities and Insurance, Securities Division",
    population: 1084225,
    retailInvestors: "an estimated 180,000 Montana retail investors",
    griffinDonations: [
      { recipient: "Republican Governors Association", amount: "$500,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations",
    keyRecipients: "national Republican committees that fund Montana candidates",
    majorFinancialCities: ["Billings", "Missoula", "Great Falls", "Bozeman"],
    financialHub: "Billings",
    stateSpecificHarm: "Montana's rural retail investor population has limited access to financial advice and relies heavily on national discount brokers, all of which route orders through Citadel Securities.",
    regulatoryAction: "Montana Attorney General Austin Knudsen and the Montana Commissioner of Securities and Insurance have jurisdiction under the Montana Securities Act (MCA §30-10-101 et seq.) to investigate broker-dealer conflicts.",
    agContactUrl: "https://dojmt.gov",
    securitiesUrl: "https://csi.mt.gov",
  },
  {
    name: "Nebraska",
    slug: "nebraska",
    abbr: "NE",
    ag: "Mike Hilgers",
    securitiesRegulator: "Nebraska Department of Banking and Finance, Securities Bureau",
    securitiesRegulatorFull: "Nebraska Department of Banking and Finance, Bureau of Securities",
    population: 1961504,
    retailInvestors: "an estimated 340,000 Nebraska retail investors",
    griffinDonations: [
      { recipient: "Pete Ricketts (R-NE Governor)", amount: "$25,000", year: "2018", office: "Nebraska Governor" },
      { recipient: "Republican Governors Association", amount: "$500,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions to Nebraska's governor and national Republican organizations",
    keyRecipients: "former Governor Pete Ricketts (now U.S. Senator) and the Republican Governors Association",
    majorFinancialCities: ["Omaha", "Lincoln", "Bellevue", "Grand Island"],
    financialHub: "Omaha",
    stateSpecificHarm: "Omaha is home to major financial institutions and sophisticated investors — but retail investors statewide are subject to the same PFOF arrangements without disclosure.",
    regulatoryAction: "Nebraska Attorney General Mike Hilgers and the Nebraska Department of Banking and Finance have authority under the Nebraska Securities Act (Neb. Rev. Stat. §8-1101 et seq.) to investigate broker-dealer practices.",
    agContactUrl: "https://ago.nebraska.gov",
    securitiesUrl: "https://banking.nebraska.gov/securities",
  },
  {
    name: "Nevada",
    slug: "nevada",
    abbr: "NV",
    ag: "Aaron Ford",
    securitiesRegulator: "Nevada Secretary of State, Securities Division",
    securitiesRegulatorFull: "Nevada Secretary of State, Securities Division",
    population: 3104614,
    retailInvestors: "an estimated 600,000 Nevada retail investors",
    griffinDonations: [
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
      { recipient: "Adam Laxalt (R-NV Senate)", amount: "$250,000", year: "2022", office: "U.S. Senate" },
    ],
    griffinTotalEstimate: "more than $1.25 million in Nevada-linked political donations",
    keyRecipients: "Senate candidate Adam Laxalt and the NRSC that invested heavily in Nevada's 2022 Senate race",
    majorFinancialCities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas"],
    financialHub: "Las Vegas",
    stateSpecificHarm: "Nevada's gaming and hospitality workers hold significant retirement savings through discount brokers. The state's large immigrant and working-class population has limited financial literacy resources to understand PFOF practices.",
    regulatoryAction: "Nevada Attorney General Aaron Ford and the Nevada Secretary of State's Securities Division have authority under the Nevada Uniform Securities Act (NRS Chapter 90) to investigate broker-dealer conflicts.",
    agContactUrl: "https://ag.nv.gov",
    securitiesUrl: "https://www.nvsos.gov/sos/licensing/securities",
  },
  {
    name: "New Hampshire",
    slug: "new-hampshire",
    abbr: "NH",
    ag: "John Formella",
    securitiesRegulator: "New Hampshire Bureau of Securities Regulation",
    securitiesRegulatorFull: "New Hampshire Bureau of Securities Regulation, Department of State",
    population: 1377529,
    retailInvestors: "an estimated 250,000 New Hampshire retail investors",
    griffinDonations: [
      { recipient: "Chris Sununu (R-NH Governor)", amount: "$100,000", year: "2022", office: "New Hampshire Governor" },
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "more than $1.1 million in New Hampshire-linked political donations",
    keyRecipients: "Governor Chris Sununu, who considered a presidential run after Griffin's support, and the NRSC",
    majorFinancialCities: ["Manchester", "Nashua", "Concord", "Portsmouth"],
    financialHub: "Manchester",
    stateSpecificHarm: "New Hampshire's 'Live Free or Die' ethos extends to its financial markets — but retail investors deserve transparency about how their orders are routed and monetized by Citadel Securities.",
    regulatoryAction: "New Hampshire Attorney General John Formella and the Bureau of Securities Regulation have authority under the New Hampshire Uniform Securities Act (RSA 421-B) to investigate broker-dealer practices.",
    agContactUrl: "https://www.doj.nh.gov",
    securitiesUrl: "https://www.sos.nh.gov/securities-regulation",
  },
  {
    name: "New Jersey",
    slug: "new-jersey",
    abbr: "NJ",
    ag: "Matthew Platkin",
    securitiesRegulator: "New Jersey Bureau of Securities",
    securitiesRegulatorFull: "New Jersey Bureau of Securities, Division of Consumer Affairs",
    population: 9288994,
    retailInvestors: "an estimated 1.9 million New Jersey retail investors — in the nation's wealthiest state per capita",
    griffinDonations: [
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "millions through national Republican organizations that target competitive New Jersey races",
    keyRecipients: "national Republican committees with New Jersey political operations",
    majorFinancialCities: ["Newark", "Jersey City", "Hoboken", "Princeton", "Trenton"],
    financialHub: "Jersey City",
    stateSpecificHarm: "New Jersey is home to some of the nation's most sophisticated retail investors — many employed in Wall Street-adjacent industries across the Hudson. These investors deserve better than the opaque PFOF arrangements that benefit Citadel at their expense.",
    regulatoryAction: "New Jersey Attorney General Matthew Platkin has been active on financial consumer protection. The New Jersey Bureau of Securities has authority under the New Jersey Uniform Securities Law (N.J.S.A. 49:3-47 et seq.) to investigate market maker conflicts.",
    agContactUrl: "https://www.njoag.gov",
    securitiesUrl: "https://www.njconsumeraffairs.gov/bos",
  },
  {
    name: "New Mexico",
    slug: "new-mexico",
    abbr: "NM",
    ag: "Raúl Torrez",
    securitiesRegulator: "New Mexico Regulation and Licensing Department, Securities Division",
    securitiesRegulatorFull: "New Mexico Regulation and Licensing Department, Securities Division",
    population: 2117522,
    retailInvestors: "an estimated 360,000 New Mexico retail investors",
    griffinDonations: [
      { recipient: "Republican Governors Association", amount: "$500,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations",
    keyRecipients: "national Republican committees that fund New Mexico candidates",
    majorFinancialCities: ["Albuquerque", "Santa Fe", "Las Cruces", "Roswell"],
    financialHub: "Albuquerque",
    stateSpecificHarm: "New Mexico has a significant Native American and Hispanic population with limited access to financial literacy resources. Retail investors in these communities face PFOF practices without adequate protection.",
    regulatoryAction: "New Mexico Attorney General Raúl Torrez and the Securities Division have authority under the New Mexico Securities Act (NMSA §58-13B-1 et seq.) to investigate broker-dealer practices.",
    agContactUrl: "https://www.nmag.gov",
    securitiesUrl: "https://www.rld.nm.gov/securities",
  },
  {
    name: "New York",
    slug: "new-york",
    abbr: "NY",
    ag: "Letitia James",
    securitiesRegulator: "New York Department of Financial Services",
    securitiesRegulatorFull: "New York Department of Financial Services (DFS)",
    population: 20201249,
    retailInvestors: "an estimated 4.2 million New York retail investors — in the nation's financial capital",
    griffinDonations: [
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2020", office: "Federal Super PAC" },
      { recipient: "Congressional Leadership Fund", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "millions through national Republican organizations that invest in New York congressional races",
    keyRecipients: "national Republican committees with New York operations",
    majorFinancialCities: ["New York City", "Buffalo", "Albany", "Rochester", "Syracuse"],
    financialHub: "New York City",
    stateSpecificHarm: "New York is the center of American finance — and yet its retail investors are subject to the same PFOF practices that benefit a Chicago-based market maker. New York retail investors on Robinhood, E*Trade, TD Ameritrade, and other platforms generate billions in order flow for Citadel Securities annually.",
    regulatoryAction: "New York Attorney General Letitia James has broad authority under the Martin Act — one of the most powerful state securities enforcement laws in the nation — to investigate PFOF practices without needing to prove intent to defraud. The New York DFS has independent regulatory authority over broker-dealers operating in the state. New York should lead a national investigation.",
    agContactUrl: "https://ag.ny.gov",
    securitiesUrl: "https://www.dfs.ny.gov",
  },
  {
    name: "North Carolina",
    slug: "north-carolina",
    abbr: "NC",
    ag: "Jeff Jackson",
    securitiesRegulator: "North Carolina Secretary of State, Securities Division",
    securitiesRegulatorFull: "North Carolina Secretary of State, Securities Division",
    population: 10439388,
    retailInvestors: "an estimated 2 million North Carolina retail investors",
    griffinDonations: [
      { recipient: "Thom Tillis (R-NC Senate)", amount: "$50,000", year: "2020", office: "U.S. Senate" },
      { recipient: "Republican Governors Association", amount: "$5,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "more than $5 million in North Carolina-linked political contributions",
    keyRecipients: "Senator Thom Tillis and the Republican Governors Association",
    majorFinancialCities: ["Charlotte", "Raleigh", "Durham", "Winston-Salem", "Greensboro"],
    financialHub: "Charlotte",
    stateSpecificHarm: "Charlotte is America's second-largest banking center. North Carolina retail investors are served by major banks and discount brokers, all of which route orders to Citadel Securities. The state's significant Black and Latino retail investor population deserves equal protection from undisclosed PFOF harms.",
    regulatoryAction: "North Carolina Attorney General Jeff Jackson and the NC Securities Division have authority under the North Carolina Securities Act (G.S. Chapter 78A) to investigate broker-dealer conflicts affecting state residents.",
    agContactUrl: "https://www.ncdoj.gov",
    securitiesUrl: "https://www.sosnc.gov/divisions/securities",
  },
  {
    name: "North Dakota",
    slug: "north-dakota",
    abbr: "ND",
    ag: "Drew Wrigley",
    securitiesRegulator: "North Dakota Securities Department",
    securitiesRegulatorFull: "North Dakota Securities Department",
    population: 779094,
    retailInvestors: "an estimated 130,000 North Dakota retail investors",
    griffinDonations: [
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations",
    keyRecipients: "national Republican organizations that support North Dakota's federal delegation",
    majorFinancialCities: ["Fargo", "Bismarck", "Grand Forks", "Minot"],
    financialHub: "Fargo",
    stateSpecificHarm: "North Dakota's oil boom has created a significant population of energy-sector workers with retirement savings — many managed through discount brokers subject to PFOF practices.",
    regulatoryAction: "North Dakota Attorney General Drew Wrigley and the North Dakota Securities Department have authority under the North Dakota Securities Act (N.D.C.C. Ch. 10-04) to investigate broker-dealer practices.",
    agContactUrl: "https://attorneygeneral.nd.gov",
    securitiesUrl: "https://www.nd.gov/securities",
  },
  {
    name: "Ohio",
    slug: "ohio",
    abbr: "OH",
    ag: "Dave Yost",
    securitiesRegulator: "Ohio Division of Securities",
    securitiesRegulatorFull: "Ohio Division of Securities, Department of Commerce",
    population: 11799448,
    retailInvestors: "an estimated 2.2 million Ohio retail investors",
    griffinDonations: [
      { recipient: "Rob Portman (R-OH Senate)", amount: "$25,000", year: "2022", office: "U.S. Senate" },
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "millions in Ohio-linked political contributions",
    keyRecipients: "Senator Rob Portman and the NRSC that invested in Ohio's 2022 Senate race",
    majorFinancialCities: ["Columbus", "Cleveland", "Cincinnati", "Akron", "Toledo"],
    financialHub: "Columbus",
    stateSpecificHarm: "Ohio's manufacturing-heavy economy has a large workforce with significant retirement savings. Ohio retail investors — from auto workers in Toledo to tech workers in Columbus — route trades through PFOF-dependent brokers without disclosure.",
    regulatoryAction: "Ohio Attorney General Dave Yost has been an active consumer protection advocate. The Ohio Division of Securities has authority under the Ohio Securities Act (O.R.C. Chapter 1707) to investigate market maker conflicts affecting Ohio investors.",
    agContactUrl: "https://www.ohioattorneygeneral.gov",
    securitiesUrl: "https://www.com.ohio.gov/securities",
  },
  {
    name: "Oklahoma",
    slug: "oklahoma",
    abbr: "OK",
    ag: "Gentner Drummond",
    securitiesRegulator: "Oklahoma Department of Securities",
    securitiesRegulatorFull: "Oklahoma Department of Securities",
    population: 3959353,
    retailInvestors: "an estimated 650,000 Oklahoma retail investors",
    griffinDonations: [
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations",
    keyRecipients: "national Republican committees that fund Oklahoma's federal delegation",
    majorFinancialCities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow"],
    financialHub: "Oklahoma City",
    stateSpecificHarm: "Oklahoma's energy sector workers and small businesses hold retirement savings through discount brokers subject to PFOF practices. The state has limited financial consumer protection infrastructure.",
    regulatoryAction: "Oklahoma Attorney General Gentner Drummond and the Oklahoma Department of Securities have authority under the Oklahoma Uniform Securities Act (71 O.S. §1-101 et seq.) to investigate broker-dealer conflicts.",
    agContactUrl: "https://www.oag.ok.gov",
    securitiesUrl: "https://www.securities.ok.gov",
  },
  {
    name: "Oregon",
    slug: "oregon",
    abbr: "OR",
    ag: "Dan Rayfield",
    securitiesRegulator: "Oregon Division of Financial Regulation",
    securitiesRegulatorFull: "Oregon Division of Financial Regulation, Department of Consumer and Business Services",
    population: 4237256,
    retailInvestors: "an estimated 780,000 Oregon retail investors",
    griffinDonations: [
      { recipient: "Congressional Leadership Fund", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations that target competitive Oregon congressional races",
    keyRecipients: "the Congressional Leadership Fund that invested in Oregon's competitive House races",
    majorFinancialCities: ["Portland", "Eugene", "Salem", "Beaverton", "Medford"],
    financialHub: "Portland",
    stateSpecificHarm: "Oregon's tech and progressive community includes many retail investors who believe they are using 'zero-commission' trading — without understanding the PFOF model that funds Citadel Securities through their order flow.",
    regulatoryAction: "Oregon Attorney General Dan Rayfield and the Oregon Division of Financial Regulation have authority under the Oregon Securities Law (ORS Chapter 59) to investigate broker-dealer practices.",
    agContactUrl: "https://www.doj.state.or.us",
    securitiesUrl: "https://dfr.oregon.gov",
  },
  {
    name: "Pennsylvania",
    slug: "pennsylvania",
    abbr: "PA",
    ag: "Dave Sunday",
    securitiesRegulator: "Pennsylvania Securities Commission",
    securitiesRegulatorFull: "Pennsylvania Securities Commission",
    population: 13002700,
    retailInvestors: "an estimated 2.5 million Pennsylvania retail investors",
    griffinDonations: [
      { recipient: "Pat Toomey (R-PA Senate)", amount: "$25,000", year: "2022", office: "U.S. Senate" },
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "millions in Pennsylvania-linked political contributions",
    keyRecipients: "Senator Pat Toomey and the NRSC that invested heavily in Pennsylvania's 2022 Senate race",
    majorFinancialCities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"],
    financialHub: "Philadelphia",
    stateSpecificHarm: "Pennsylvania's large industrial working class — from Pittsburgh steel country to Philadelphia's port district — has significant retirement savings managed through 401(k) plans and discount brokers. PFOF practices extract value from these workers' savings without transparency.",
    regulatoryAction: "Pennsylvania Attorney General Dave Sunday and the Pennsylvania Securities Commission have authority under the Pennsylvania Securities Act of 1972 (70 P.S. §1-101 et seq.) to investigate broker-dealer conflicts.",
    agContactUrl: "https://www.attorneygeneral.gov",
    securitiesUrl: "https://www.psc.gov",
  },
  {
    name: "Rhode Island",
    slug: "rhode-island",
    abbr: "RI",
    ag: "Peter Neronha",
    securitiesRegulator: "Rhode Island Department of Business Regulation, Securities Division",
    securitiesRegulatorFull: "Rhode Island Department of Business Regulation, Securities Division",
    population: 1097379,
    retailInvestors: "an estimated 195,000 Rhode Island retail investors",
    griffinDonations: [
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2020", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations",
    keyRecipients: "national Republican committees",
    majorFinancialCities: ["Providence", "Warwick", "Cranston", "Pawtucket"],
    financialHub: "Providence",
    stateSpecificHarm: "Rhode Island retail investors — many in Providence's manufacturing and healthcare sectors — rely on discount brokers for retirement savings and face undisclosed PFOF arrangements.",
    regulatoryAction: "Rhode Island Attorney General Peter Neronha and the DBR Securities Division have authority under the Rhode Island Uniform Securities Act (R.I. Gen. Laws §7-11-101 et seq.) to investigate broker-dealer practices.",
    agContactUrl: "https://riag.ri.gov",
    securitiesUrl: "https://dbr.ri.gov/securities",
  },
  {
    name: "South Carolina",
    slug: "south-carolina",
    abbr: "SC",
    ag: "Alan Wilson",
    securitiesRegulator: "South Carolina Secretary of State, Securities Division",
    securitiesRegulatorFull: "South Carolina Secretary of State, Securities Division",
    population: 5118425,
    retailInvestors: "an estimated 875,000 South Carolina retail investors",
    griffinDonations: [
      { recipient: "Lindsey Graham (R-SC Senate)", amount: "$50,000", year: "2020", office: "U.S. Senate" },
      { recipient: "Tim Scott (R-SC Senate)", amount: "$25,000", year: "2020", office: "U.S. Senate" },
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "more than $1.5 million in South Carolina-linked political contributions",
    keyRecipients: "Senators Lindsey Graham and Tim Scott — two of the most prominent Republican senators — and the Republican National Committee",
    majorFinancialCities: ["Columbia", "Charleston", "Greenville", "Spartanburg"],
    financialHub: "Charleston",
    stateSpecificHarm: "South Carolina's retiree and military veteran population has significant retirement savings managed through discount brokers, all subject to PFOF practices that benefit a company investing heavily in politicians who oversee financial regulation.",
    regulatoryAction: "South Carolina Attorney General Alan Wilson and the SC Securities Division have authority under the South Carolina Uniform Securities Act (S.C. Code Ann. §35-1-101 et seq.) to investigate broker-dealer conflicts.",
    agContactUrl: "https://www.scag.gov",
    securitiesUrl: "https://www.sos.sc.gov/securities",
  },
  {
    name: "South Dakota",
    slug: "south-dakota",
    abbr: "SD",
    ag: "Marty Jackley",
    securitiesRegulator: "South Dakota Division of Securities",
    securitiesRegulatorFull: "South Dakota Division of Securities, Department of Labor and Regulation",
    population: 886667,
    retailInvestors: "an estimated 155,000 South Dakota retail investors",
    griffinDonations: [
      { recipient: "Kristi Noem (R-SD Governor)", amount: "$50,000", year: "2022", office: "South Dakota Governor" },
      { recipient: "Republican Governors Association", amount: "$500,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions to Governor Noem and national Republican organizations",
    keyRecipients: "Governor Kristi Noem and the Republican Governors Association",
    majorFinancialCities: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings"],
    financialHub: "Sioux Falls",
    stateSpecificHarm: "South Dakota is known for favorable financial industry laws — but its retail investor population deserves protection from undisclosed PFOF practices just as much as investors in more regulated states.",
    regulatoryAction: "South Dakota Attorney General Marty Jackley and the South Dakota Division of Securities have authority under the South Dakota Uniform Securities Act (S.D.C.L. Ch. 47-31B) to investigate broker-dealer practices.",
    agContactUrl: "https://atg.sd.gov",
    securitiesUrl: "https://dlr.sd.gov/securities",
  },
  {
    name: "Tennessee",
    slug: "tennessee",
    abbr: "TN",
    ag: "Jonathan Skrmetti",
    securitiesRegulator: "Tennessee Department of Commerce and Insurance, Securities Division",
    securitiesRegulatorFull: "Tennessee Department of Commerce and Insurance, Securities Division",
    population: 6910840,
    retailInvestors: "an estimated 1.2 million Tennessee retail investors",
    griffinDonations: [
      { recipient: "Marsha Blackburn (R-TN Senate)", amount: "$10,000", year: "2018", office: "U.S. Senate" },
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "millions in Tennessee-linked political contributions",
    keyRecipients: "Senator Marsha Blackburn and national Republican organizations",
    majorFinancialCities: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"],
    financialHub: "Nashville",
    stateSpecificHarm: "Nashville's booming economy and growing professional class includes a significant retail investor population. Tennessee residents face PFOF-based order routing without state enforcement action.",
    regulatoryAction: "Tennessee Attorney General Jonathan Skrmetti and the Tennessee Securities Division have authority under the Tennessee Securities Act of 1980 (T.C.A. §48-1-101 et seq.) to investigate broker-dealer conflicts.",
    agContactUrl: "https://www.tn.gov/attorneygeneral",
    securitiesUrl: "https://www.tn.gov/commerce/securities.html",
  },
  {
    name: "Texas",
    slug: "texas",
    abbr: "TX",
    ag: "Ken Paxton",
    securitiesRegulator: "Texas State Securities Board",
    securitiesRegulatorFull: "Texas State Securities Board",
    population: 29145505,
    retailInvestors: "an estimated 5.5 million Texas retail investors — the third-largest state retail investor population",
    griffinDonations: [
      { recipient: "John Cornyn (R-TX Senate)", amount: "$50,000", year: "2020", office: "U.S. Senate" },
      { recipient: "Ted Cruz (R-TX Senate)", amount: "$25,000", year: "2018", office: "U.S. Senate" },
      { recipient: "Greg Abbott (R-TX Governor)", amount: "$100,000", year: "2022", office: "Texas Governor" },
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "more than $1.2 million in Texas-linked political contributions, plus tens of millions through national organizations that fund Texas candidates",
    keyRecipients: "Senators John Cornyn and Ted Cruz, Governor Greg Abbott, and national Republican organizations with heavy Texas investments",
    majorFinancialCities: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "El Paso"],
    financialHub: "Houston/Dallas",
    stateSpecificHarm: "Texas retail investors are the third most affected population in the nation. From Houston energy workers to Dallas tech professionals to Austin entrepreneurs, millions of Texas retail investors' orders are routed to Citadel Securities through PFOF arrangements. The Texas State Securities Board, one of the nation's most aggressive regulators historically, has taken no action on PFOF.",
    regulatoryAction: "Texas Attorney General Ken Paxton and the Texas State Securities Board have powerful enforcement tools under the Texas Securities Act (Tex. Rev. Civ. Stat. Art. 581) and the Texas Deceptive Trade Practices Act to investigate PFOF. The Texas SSB's history of aggressive enforcement makes it well-positioned to lead a multistate action.",
    agContactUrl: "https://www.texasattorneygeneral.gov",
    securitiesUrl: "https://www.ssb.texas.gov",
  },
  {
    name: "Utah",
    slug: "utah",
    abbr: "UT",
    ag: "Derek Brown",
    securitiesRegulator: "Utah Division of Securities",
    securitiesRegulatorFull: "Utah Division of Securities, Department of Commerce",
    population: 3271616,
    retailInvestors: "an estimated 590,000 Utah retail investors",
    griffinDonations: [
      { recipient: "Mitt Romney (R-UT Senate)", amount: "$50,000", year: "2018", office: "U.S. Senate" },
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "more than $1.5 million in Utah-linked political contributions",
    keyRecipients: "Senator Mitt Romney, who served on the Senate Banking Committee, and national Republican organizations",
    majorFinancialCities: ["Salt Lake City", "Provo", "Ogden", "St. George"],
    financialHub: "Salt Lake City",
    stateSpecificHarm: "Utah's tech sector ('Silicon Slopes') has created a growing population of retail investors. Utah's strong culture of financial planning and investment makes retail investors particularly vulnerable to undisclosed PFOF harms.",
    regulatoryAction: "Utah Attorney General Derek Brown and the Utah Division of Securities have authority under the Utah Uniform Securities Act (Utah Code Ann. §61-1-1 et seq.) to investigate broker-dealer practices.",
    agContactUrl: "https://attorneygeneral.utah.gov",
    securitiesUrl: "https://securities.utah.gov",
  },
  {
    name: "Vermont",
    slug: "vermont",
    abbr: "VT",
    ag: "Charity Clark",
    securitiesRegulator: "Vermont Department of Financial Regulation, Securities Division",
    securitiesRegulatorFull: "Vermont Department of Financial Regulation, Securities Division",
    population: 643077,
    retailInvestors: "an estimated 115,000 Vermont retail investors",
    griffinDonations: [
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2020", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations",
    keyRecipients: "national Republican committees",
    majorFinancialCities: ["Burlington", "South Burlington", "Rutland", "Montpelier"],
    financialHub: "Burlington",
    stateSpecificHarm: "Vermont's progressive investor community places high value on transparency and ethical business practices — values fundamentally at odds with Citadel's undisclosed PFOF arrangements.",
    regulatoryAction: "Vermont Attorney General Charity Clark and the Vermont DFR Securities Division have authority under the Vermont Uniform Securities Act (9 V.S.A. §5101 et seq.) to investigate broker-dealer practices.",
    agContactUrl: "https://ago.vermont.gov",
    securitiesUrl: "https://dfr.vermont.gov/financial-product/securities",
  },
  {
    name: "Virginia",
    slug: "virginia",
    abbr: "VA",
    ag: "Jason Miyares",
    securitiesRegulator: "Virginia State Corporation Commission, Division of Securities and Retail Franchising",
    securitiesRegulatorFull: "Virginia State Corporation Commission, Division of Securities and Retail Franchising",
    population: 8631393,
    retailInvestors: "an estimated 1.7 million Virginia retail investors — including significant federal government employee investor population",
    griffinDonations: [
      { recipient: "Glenn Youngkin (R-VA Governor)", amount: "$100,000", year: "2021", office: "Virginia Governor" },
      { recipient: "Republican Governors Association", amount: "$5,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "more than $5.1 million in Virginia-linked political contributions",
    keyRecipients: "Governor Glenn Youngkin and the Republican Governors Association that invested in Virginia's 2021 race",
    majorFinancialCities: ["Fairfax", "Arlington", "Richmond", "Norfolk", "Virginia Beach"],
    financialHub: "Northern Virginia/Fairfax",
    stateSpecificHarm: "Virginia has the largest population of federal government employees and contractors in the nation — many of whom invest through Thrift Savings Plan-adjacent brokers and retail platforms subject to PFOF. The Northern Virginia tech corridor also houses sophisticated retail investors who deserve better execution.",
    regulatoryAction: "Virginia Attorney General Jason Miyares and the Virginia SCC Division of Securities have broad authority under the Virginia Securities Act (Va. Code Ann. §13.1-501 et seq.) to investigate broker-dealer conflicts affecting Virginia investors.",
    agContactUrl: "https://www.oag.state.va.us",
    securitiesUrl: "https://www.scc.virginia.gov/pages/Securities",
  },
  {
    name: "Washington",
    slug: "washington",
    abbr: "WA",
    ag: "Nick Brown",
    securitiesRegulator: "Washington State Department of Financial Institutions, Securities Division",
    securitiesRegulatorFull: "Washington State Department of Financial Institutions, Securities Division",
    population: 7705281,
    retailInvestors: "an estimated 1.5 million Washington retail investors — concentrated in the Seattle tech corridor",
    griffinDonations: [
      { recipient: "Congressional Leadership Fund", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "millions through national Republican organizations investing in competitive Washington races",
    keyRecipients: "national Republican committees targeting Washington's competitive House and Senate seats",
    majorFinancialCities: ["Seattle", "Bellevue", "Tacoma", "Spokane", "Redmond"],
    financialHub: "Seattle",
    stateSpecificHarm: "Washington's tech sector — Amazon, Microsoft, Boeing employees — represents some of the nation's most active retail investors. These sophisticated investors are entitled to best execution and transparent order routing — not undisclosed PFOF arrangements.",
    regulatoryAction: "Washington Attorney General Nick Brown and the Washington DFI Securities Division have authority under the Washington Securities Act (RCW Chapter 21.20) to investigate broker-dealer practices. Washington has historically been among the more active states on securities enforcement.",
    agContactUrl: "https://www.atg.wa.gov",
    securitiesUrl: "https://dfi.wa.gov/securities",
  },
  {
    name: "West Virginia",
    slug: "west-virginia",
    abbr: "WV",
    ag: "Patrick Morrisey",
    securitiesRegulator: "West Virginia Securities Commission",
    securitiesRegulatorFull: "West Virginia Securities Commission",
    population: 1793716,
    retailInvestors: "an estimated 280,000 West Virginia retail investors",
    griffinDonations: [
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations",
    keyRecipients: "national Republican committees that fund West Virginia's federal delegation",
    majorFinancialCities: ["Charleston", "Huntington", "Morgantown", "Parkersburg"],
    financialHub: "Charleston",
    stateSpecificHarm: "West Virginia's coal and energy workers hold significant retirement savings — many through employer-sponsored plans and discount brokers all subject to PFOF. The state's retail investor population has limited access to financial advocacy.",
    regulatoryAction: "West Virginia Attorney General Patrick Morrisey and the West Virginia Securities Commission have authority under the West Virginia Uniform Securities Act (W. Va. Code §32-1-101 et seq.) to investigate broker-dealer conflicts.",
    agContactUrl: "https://ago.wv.gov",
    securitiesUrl: "https://wvsecurities.gov",
  },
  {
    name: "Wisconsin",
    slug: "wisconsin",
    abbr: "WI",
    ag: "Josh Kaul",
    securitiesRegulator: "Wisconsin Department of Financial Institutions, Division of Securities",
    securitiesRegulatorFull: "Wisconsin Department of Financial Institutions, Division of Securities",
    population: 5893718,
    retailInvestors: "an estimated 1.1 million Wisconsin retail investors",
    griffinDonations: [
      { recipient: "Scott Walker (R-WI Governor)", amount: "$500,000", year: "2018", office: "Wisconsin Governor" },
      { recipient: "Ron Johnson (R-WI Senate)", amount: "$250,000", year: "2022", office: "U.S. Senate" },
      { recipient: "Republican Governors Association", amount: "$5,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "more than $5.75 million in Wisconsin-linked political contributions",
    keyRecipients: "former Governor Scott Walker, Senator Ron Johnson — who sits on the Senate Banking Committee — and the Republican Governors Association",
    majorFinancialCities: ["Milwaukee", "Madison", "Green Bay", "Racine", "Kenosha"],
    financialHub: "Milwaukee",
    stateSpecificHarm: "Wisconsin's manufacturing and dairy economy has a large working-class retail investor population. Griffin's significant political investment in Wisconsin — including to Senator Ron Johnson of the Senate Banking Committee — raises serious questions about regulatory capture.",
    regulatoryAction: "Wisconsin Attorney General Josh Kaul and the Wisconsin DFI Division of Securities have authority under the Wisconsin Uniform Securities Law (Wis. Stat. Ch. 551) to investigate broker-dealer conflicts. Given Griffin's donations to Wisconsin Banking Committee members, the AG's independence is particularly valuable.",
    agContactUrl: "https://www.doj.state.wi.us",
    securitiesUrl: "https://www.wdfi.org/securities",
  },
  {
    name: "Wyoming",
    slug: "wyoming",
    abbr: "WY",
    ag: "Bridget Hill",
    securitiesRegulator: "Wyoming Secretary of State, Securities Division",
    securitiesRegulatorFull: "Wyoming Secretary of State, Securities Division",
    population: 576851,
    retailInvestors: "an estimated 100,000 Wyoming retail investors",
    griffinDonations: [
      { recipient: "Republican Governors Association", amount: "$500,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "contributions through national Republican organizations",
    keyRecipients: "national Republican committees that fund Wyoming candidates",
    majorFinancialCities: ["Cheyenne", "Casper", "Laramie", "Gillette"],
    financialHub: "Cheyenne",
    stateSpecificHarm: "Wyoming's energy sector workers and ranchers hold retirement savings through discount brokers subject to PFOF practices. The state's minimal regulation ethos has not been extended to protecting retail investors from market maker conflicts.",
    regulatoryAction: "Wyoming Attorney General Bridget Hill and the Wyoming Secretary of State's Securities Division have authority under the Wyoming Uniform Securities Act (W.S. §17-4-101 et seq.) to investigate broker-dealer practices.",
    agContactUrl: "https://ag.wyo.gov",
    securitiesUrl: "https://sos.wyo.gov/Securities",
  },
  // DC
  {
    name: "Washington D.C.",
    slug: "washington-dc",
    abbr: "DC",
    ag: "Brian Schwalb",
    securitiesRegulator: "DC Department of Insurance, Securities and Banking",
    securitiesRegulatorFull: "DC Department of Insurance, Securities and Banking (DISB)",
    population: 689545,
    retailInvestors: "an estimated 150,000 DC retail investors — disproportionately employed in government and policy roles",
    griffinDonations: [
      { recipient: "Congressional Leadership Fund", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
      { recipient: "National Republican Senatorial Committee", amount: "$1,000,000", year: "2022", office: "Federal Super PAC" },
    ],
    griffinTotalEstimate: "millions through national Republican organizations with significant DC-based operations",
    keyRecipients: "national Republican House and Senate super PACs that fund campaigns competing for DC-adjacent congressional seats",
    majorFinancialCities: ["Washington DC"],
    financialHub: "Washington DC",
    stateSpecificHarm: "DC retail investors — including government regulators, congressional staffers, and policy professionals — have a unique window into the gap between Citadel's political influence and regulatory action. DC residents deserve the same investor protections as residents of the 50 states.",
    regulatoryAction: "DC Attorney General Brian Schwalb and the DC DISB have authority under the DC Securities Act (D.C. Code §31-5601.01 et seq.) to investigate broker-dealer practices. DC's unique position as both a political and regulatory center makes its AG a critical voice in any PFOF investigation.",
    agContactUrl: "https://oag.dc.gov",
    securitiesUrl: "https://disb.dc.gov",
  },
  // Puerto Rico
  {
    name: "Puerto Rico",
    slug: "puerto-rico",
    abbr: "PR",
    ag: "Domingo Emanuelli Hernández",
    securitiesRegulator: "Puerto Rico Office of the Commissioner of Financial Institutions",
    securitiesRegulatorFull: "Puerto Rico Office of the Commissioner of Financial Institutions (OCIF)",
    population: 3285874,
    retailInvestors: "an estimated 400,000 Puerto Rico retail investors",
    griffinDonations: [
      { recipient: "Republican National Committee", amount: "$1,500,000", year: "2022", office: "Federal Committee" },
    ],
    griffinTotalEstimate: "contributions through national organizations",
    keyRecipients: "national Republican organizations",
    majorFinancialCities: ["San Juan", "Bayamón", "Ponce", "Carolina"],
    financialHub: "San Juan",
    stateSpecificHarm: "Puerto Rico retail investors face unique vulnerabilities: limited SEC jurisdiction arguments, recovery from Hurricane Maria, and a financial crisis that has left many residents managing what savings they have through national discount brokers — all subject to PFOF practices.",
    regulatoryAction: "Puerto Rico Attorney General Domingo Emanuelli and the OCIF have authority under the Puerto Rico Uniform Securities Act (10 L.P.R.A. §860 et seq.) to investigate broker-dealer practices affecting Puerto Rico residents. Puerto Rico's unique financial regulatory status makes coordination with federal regulators essential.",
    agContactUrl: "https://www.justicia.pr.gov",
    securitiesUrl: "https://ocif.pr.gov",
  },
];

export function getCitadelStateBySlug(slug: string): CitadelStateData | undefined {
  return citadelStatesData.find((s) => s.slug === slug);
}
