export interface StateData {
  name: string;
  slug: string;
  bar: string;
  barUrl: string;
  barAddr: string;
  jc: string;
  jcAddr: string;
}

export const statesData: StateData[] = [
  { name: "Alabama", slug: "alabama", bar: "Alabama State Bar", barUrl: "https://www.alabar.org", barAddr: "415 Dexter Avenue, Montgomery, AL 36104", jc: "Alabama Judicial Inquiry Commission", jcAddr: "P.O. Box 303419, Montgomery, AL 36130" },
  { name: "Alaska", slug: "alaska", bar: "Alaska Bar Association", barUrl: "https://alaskabar.org", barAddr: "P.O. Box 100279, Anchorage, AK 99510", jc: "Alaska Commission on Judicial Conduct", jcAddr: "820 W 4th Avenue, Anchorage, AK 99501" },
  { name: "Arizona", slug: "arizona", bar: "State Bar of Arizona", barUrl: "https://www.azbar.org", barAddr: "4201 N 24th Street, Suite 100, Phoenix, AZ 85016", jc: "Arizona Commission on Judicial Conduct", jcAddr: "1501 W. Washington Street, Suite 221, Phoenix, AZ 85007" },
  { name: "Arkansas", slug: "arkansas", bar: "Arkansas Supreme Court Committee on Professional Conduct", barUrl: "https://www.arkbar.com", barAddr: "Donaghey Plaza South, Suite 1300, Little Rock, AR 72201", jc: "Arkansas Judicial Discipline and Disability Commission", jcAddr: "323 Center Street, Suite 1060, Little Rock, AR 72201" },
  { name: "California", slug: "california", bar: "State Bar of California", barUrl: "https://www.calbar.ca.gov", barAddr: "845 S. Figueroa Street, Los Angeles, CA 90017", jc: "California Commission on Judicial Performance", jcAddr: "455 Golden Gate Avenue, Suite 14400, San Francisco, CA 94102" },
  { name: "Colorado", slug: "colorado", bar: "Colorado Supreme Court Office of Attorney Regulation Counsel", barUrl: "https://www.coloradosupremecourt.com", barAddr: "1300 Broadway, Suite 500, Denver, CO 80203", jc: "Colorado Commission on Judicial Discipline", jcAddr: "1300 Broadway, Suite 510, Denver, CO 80203" },
  { name: "Connecticut", slug: "connecticut", bar: "Statewide Grievance Committee", barUrl: "https://www.jud.ct.gov/sgc", barAddr: "287 Main Street, 2nd Floor, East Hartford, CT 06118", jc: "Connecticut Judicial Review Council", jcAddr: "100 Washington Street, Hartford, CT 06106" },
  { name: "Delaware", slug: "delaware", bar: "Office of Disciplinary Counsel, Delaware Supreme Court", barUrl: "https://courts.delaware.gov/odc", barAddr: "200 W. 9th Street, Suite 300-B, Wilmington, DE 19801", jc: "Delaware Court on the Judiciary", jcAddr: "820 N. French Street, Wilmington, DE 19801" },
  { name: "Florida", slug: "florida", bar: "The Florida Bar", barUrl: "https://www.floridabar.org", barAddr: "651 E. Jefferson Street, Tallahassee, FL 32399", jc: "Florida Judicial Qualifications Commission", jcAddr: "1110 Thomasville Road, Tallahassee, FL 32303" },
  { name: "Georgia", slug: "georgia", bar: "State Bar of Georgia", barUrl: "https://www.gabar.org", barAddr: "104 Marietta Street NW, Suite 100, Atlanta, GA 30303", jc: "Georgia Judicial Qualifications Commission", jcAddr: "244 Washington Street SW, Suite 324, Atlanta, GA 30334" },
  { name: "Hawaii", slug: "hawaii", bar: "Office of Disciplinary Counsel, Supreme Court of Hawaii", barUrl: "https://www.courts.state.hi.us", barAddr: "1100 Alakea Street, Suite 1000, Honolulu, HI 96813", jc: "Hawaii Commission on Judicial Conduct", jcAddr: "417 S. King Street, Honolulu, HI 96813" },
  { name: "Idaho", slug: "idaho", bar: "Idaho State Bar", barUrl: "https://isb.idaho.gov", barAddr: "P.O. Box 895, Boise, ID 83701", jc: "Idaho Judicial Council", jcAddr: "451 W. State Street, Boise, ID 83720" },
  { name: "Illinois", slug: "illinois", bar: "Attorney Registration and Disciplinary Commission", barUrl: "https://www.iardc.org", barAddr: "130 E. Randolph Drive, Suite 1500, Chicago, IL 60601", jc: "Illinois Courts Commission", jcAddr: "222 N. LaSalle Street, Suite 2110, Chicago, IL 60601" },
  { name: "Indiana", slug: "indiana", bar: "Indiana Supreme Court Disciplinary Commission", barUrl: "https://www.in.gov/judiciary/disciplinary", barAddr: "30 S. Meridian Street, Suite 850, Indianapolis, IN 46204", jc: "Indiana Commission on Judicial Qualifications", jcAddr: "30 S. Meridian Street, Suite 850, Indianapolis, IN 46204" },
  { name: "Iowa", slug: "iowa", bar: "Iowa Supreme Court Attorney Disciplinary Board", barUrl: "https://www.iowacourtsonline.org", barAddr: "1111 E. Court Avenue, Des Moines, IA 50319", jc: "Iowa Commission on Judicial Qualifications", jcAddr: "1111 E. Court Avenue, Des Moines, IA 50319" },
  { name: "Kansas", slug: "kansas", bar: "Office of the Disciplinary Administrator", barUrl: "https://www.kscourts.org/disciplinary", barAddr: "701 SW Jackson Street, Suite 400, Topeka, KS 66603", jc: "Kansas Commission on Judicial Qualifications", jcAddr: "301 SW 10th Avenue, Room 374, Topeka, KS 66612" },
  { name: "Kentucky", slug: "kentucky", bar: "Kentucky Bar Association", barUrl: "https://www.kybar.org", barAddr: "514 W. Main Street, Frankfort, KY 40601", jc: "Kentucky Judicial Conduct Commission", jcAddr: "1001 Vandalay Drive, Frankfort, KY 40601" },
  { name: "Louisiana", slug: "louisiana", bar: "Louisiana Attorney Disciplinary Board", barUrl: "https://www.ladb.org", barAddr: "2800 Veterans Memorial Blvd., Suite 310, Metairie, LA 70002", jc: "Louisiana Judiciary Commission", jcAddr: "2800 Veterans Memorial Blvd., Suite 220, Metairie, LA 70002" },
  { name: "Maine", slug: "maine", bar: "Board of Overseers of the Bar", barUrl: "https://www.maine.gov/tools/whatsnew/index.php?topic=meBar", barAddr: "97 Winthrop Street, Augusta, ME 04330", jc: "Maine Committee on Judicial Responsibility and Disability", jcAddr: "142 Federal Street, Portland, ME 04101" },
  { name: "Maryland", slug: "maryland", bar: "Attorney Grievance Commission of Maryland", barUrl: "https://www.courts.state.md.us/attygrievance", barAddr: "200 Harry S. Truman Pkwy., Suite 300, Annapolis, MD 21401", jc: "Maryland Commission on Judicial Disabilities", jcAddr: "100 Community Place, Crownsville, MD 21032" },
  { name: "Massachusetts", slug: "massachusetts", bar: "Board of Bar Overseers", barUrl: "https://www.massbbo.org", barAddr: "99 High Street, Boston, MA 02110", jc: "Massachusetts Commission on Judicial Conduct", jcAddr: "1 Ashburton Place, Room 1009, Boston, MA 02108" },
  { name: "Michigan", slug: "michigan", bar: "Attorney Grievance Commission of Michigan", barUrl: "https://www.agcmi.com", barAddr: "535 Griswold Street, Suite 1700, Detroit, MI 48226", jc: "Michigan Judicial Tenure Commission", jcAddr: "3034 W. Grand Blvd., Suite 8-450, Detroit, MI 48202" },
  { name: "Minnesota", slug: "minnesota", bar: "Minnesota Lawyers Professional Responsibility Board", barUrl: "https://www.lprb.mn.gov", barAddr: "1500 Landmark Towers, 345 St. Peter Street, St. Paul, MN 55102", jc: "Minnesota Board on Judicial Standards", jcAddr: "180 E. 5th Street, Suite 1055, St. Paul, MN 55101" },
  { name: "Mississippi", slug: "mississippi", bar: "Mississippi Bar", barUrl: "https://www.msbar.org", barAddr: "P.O. Box 2168, Jackson, MS 39225", jc: "Mississippi Commission on Judicial Performance", jcAddr: "660 North Street, Suite 104, Jackson, MS 39202" },
  { name: "Missouri", slug: "missouri", bar: "Missouri Office of Chief Disciplinary Counsel", barUrl: "https://www.ocdc.mo.gov", barAddr: "3335 American Avenue, Jefferson City, MO 65109", jc: "Missouri Commission on Retirement, Removal and Discipline", jcAddr: "P.O. Box 150, Jefferson City, MO 65102" },
  { name: "Montana", slug: "montana", bar: "Office of Disciplinary Counsel, Montana Supreme Court", barUrl: "https://courts.mt.gov/odc", barAddr: "P.O. Box 577, Helena, MT 59624", jc: "Montana Judicial Standards Commission", jcAddr: "P.O. Box 1794, Helena, MT 59624" },
  { name: "Nebraska", slug: "nebraska", bar: "Nebraska Counsel for Discipline", barUrl: "https://supremecourt.nebraska.gov", barAddr: "635 S. 14th Street, Suite 200, Lincoln, NE 68508", jc: "Nebraska Commission on Judicial Qualifications", jcAddr: "635 S. 14th Street, Suite 200, Lincoln, NE 68508" },
  { name: "Nevada", slug: "nevada", bar: "State Bar of Nevada", barUrl: "https://nvbar.org", barAddr: "3100 W. Charleston Blvd., Suite 100, Las Vegas, NV 89102", jc: "Nevada Commission on Judicial Discipline", jcAddr: "P.O. Box 48, Carson City, NV 89702" },
  { name: "New Hampshire", slug: "new-hampshire", bar: "New Hampshire Supreme Court Professional Conduct Committee", barUrl: "https://www.courts.nh.gov/pcc", barAddr: "4 Chenell Drive, Suite 102, Concord, NH 03301", jc: "New Hampshire Judicial Conduct Committee", jcAddr: "One Granite Place, Suite N400, Concord, NH 03301" },
  { name: "New Jersey", slug: "new-jersey", bar: "Office of Attorney Ethics, New Jersey Supreme Court", barUrl: "https://www.njcourts.gov/attorneys/oae.html", barAddr: "P.O. Box 963, Trenton, NJ 08625", jc: "Advisory Committee on Judicial Conduct", jcAddr: "P.O. Box 037, Trenton, NJ 08625" },
  { name: "New Mexico", slug: "new-mexico", bar: "Disciplinary Board of the New Mexico Supreme Court", barUrl: "https://www.nmbar.org", barAddr: "400 Gold Avenue SW, Suite 1100, Albuquerque, NM 87102", jc: "New Mexico Judicial Standards Commission", jcAddr: "P.O. Box 25444, Albuquerque, NM 87125" },
  { name: "New York", slug: "new-york", bar: "Attorney Grievance Committee, Appellate Division", barUrl: "https://www.nycourts.gov/courts/ad1/committees&programs/AGC", barAddr: "180 Maiden Lane, New York, NY 10038", jc: "New York State Commission on Judicial Conduct", jcAddr: "61 Broadway, Suite 1200, New York, NY 10006" },
  { name: "North Carolina", slug: "north-carolina", bar: "North Carolina State Bar", barUrl: "https://www.ncbar.gov", barAddr: "P.O. Box 25908, Raleigh, NC 27611", jc: "North Carolina Judicial Standards Commission", jcAddr: "P.O. Box 20961, Raleigh, NC 27619" },
  { name: "North Dakota", slug: "north-dakota", bar: "Disciplinary Board of the North Dakota Supreme Court", barUrl: "https://www.ndcourts.gov/court/boards/disciplinary", barAddr: "600 E. Boulevard Avenue, Dept. 180, Bismarck, ND 58505", jc: "North Dakota Commission on Judicial Conduct", jcAddr: "600 E. Boulevard Avenue, Dept. 180, Bismarck, ND 58505" },
  { name: "Ohio", slug: "ohio", bar: "Office of Disciplinary Counsel, Ohio Supreme Court", barUrl: "https://www.supremecourt.ohio.gov/AttySvcs/AttyReg/Discipline", barAddr: "250 Civic Center Drive, Suite 325, Columbus, OH 43215", jc: "Ohio Board of Professional Conduct", jcAddr: "250 Civic Center Drive, Suite 325, Columbus, OH 43215" },
  { name: "Oklahoma", slug: "oklahoma", bar: "Oklahoma Bar Association", barUrl: "https://www.okbar.org", barAddr: "P.O. Box 53036, Oklahoma City, OK 73152", jc: "Oklahoma Council on Judicial Complaints", jcAddr: "1915 N. Stiles Avenue, Suite 305, Oklahoma City, OK 73105" },
  { name: "Oregon", slug: "oregon", bar: "Oregon State Bar", barUrl: "https://www.osbar.org", barAddr: "P.O. Box 231935, Tigard, OR 97281", jc: "Oregon Commission on Judicial Fitness and Disability", jcAddr: "1162 Court Street NE, Salem, OR 97301" },
  { name: "Pennsylvania", slug: "pennsylvania", bar: "Disciplinary Board of the Supreme Court of Pennsylvania", barUrl: "https://www.padisciplinaryboard.org", barAddr: "Pennsylvania Judicial Center, 601 Commonwealth Avenue, Harrisburg, PA 17120", jc: "Pennsylvania Court of Judicial Discipline", jcAddr: "Pennsylvania Judicial Center, 601 Commonwealth Avenue, Harrisburg, PA 17120" },
  { name: "Rhode Island", slug: "rhode-island", bar: "Disciplinary Board, Rhode Island Supreme Court", barUrl: "https://www.courts.ri.gov/publicdefender/disciplinaryboard", barAddr: "24 Weybosset Street, Providence, RI 02903", jc: "Rhode Island Commission on Judicial Tenure and Discipline", jcAddr: "250 Benefit Street, Providence, RI 02903" },
  { name: "South Carolina", slug: "south-carolina", bar: "Office of Disciplinary Counsel, South Carolina Supreme Court", barUrl: "https://www.sccourts.org/odc", barAddr: "P.O. Box 12159, Columbia, SC 29211", jc: "South Carolina Commission on Judicial Conduct", jcAddr: "P.O. Box 12159, Columbia, SC 29211" },
  { name: "South Dakota", slug: "south-dakota", bar: "State Bar of South Dakota", barUrl: "https://www.statebarofsouthdakota.com", barAddr: "222 E. Capitol Avenue, Suite 14, Pierre, SD 57501", jc: "South Dakota Judicial Qualifications Commission", jcAddr: "500 E. Capitol Avenue, Pierre, SD 57501" },
  { name: "Tennessee", slug: "tennessee", bar: "Board of Professional Responsibility, Tennessee Supreme Court", barUrl: "https://www.tbpr.org", barAddr: "10 Cadillac Drive, Suite 220, Brentwood, TN 37027", jc: "Tennessee Court of the Judiciary", jcAddr: "511 Union Street, Suite 600, Nashville, TN 37219" },
  { name: "Texas", slug: "texas", bar: "State Bar of Texas", barUrl: "https://www.texasbar.com", barAddr: "P.O. Box 12487, Austin, TX 78711", jc: "State Commission on Judicial Conduct", jcAddr: "P.O. Box 12265, Austin, TX 78711" },
  { name: "Utah", slug: "utah", bar: "Utah State Bar, Office of Professional Conduct", barUrl: "https://www.utahbar.org/opc", barAddr: "645 S. 200 East, Salt Lake City, UT 84111", jc: "Utah Judicial Conduct Commission", jcAddr: "645 S. 200 East, Suite 104, Salt Lake City, UT 84111" },
  { name: "Vermont", slug: "vermont", bar: "Professional Responsibility Board, Vermont Supreme Court", barUrl: "https://www.vermontjudiciary.org/attorneys/professional-responsibility-program", barAddr: "109 State Street, Montpelier, VT 05609", jc: "Vermont Judicial Conduct Board", jcAddr: "109 State Street, Montpelier, VT 05609" },
  { name: "Virginia", slug: "virginia", bar: "Virginia State Bar", barUrl: "https://www.vsb.org", barAddr: "1111 E. Main Street, Suite 700, Richmond, VA 23219", jc: "Judicial Inquiry and Review Commission of Virginia", jcAddr: "100 N. 9th Street, Richmond, VA 23219" },
  { name: "Washington", slug: "washington", bar: "Washington State Bar Association", barUrl: "https://www.wsba.org", barAddr: "1325 4th Avenue, Suite 600, Seattle, WA 98101", jc: "Washington State Commission on Judicial Conduct", jcAddr: "P.O. Box 1817, Olympia, WA 98507" },
  { name: "West Virginia", slug: "west-virginia", bar: "Lawyer Disciplinary Board, West Virginia Supreme Court of Appeals", barUrl: "https://www.wvodc.org", barAddr: "4700 MacCorkle Avenue SE, Charleston, WV 25304", jc: "West Virginia Judicial Investigation Commission", jcAddr: "4700 MacCorkle Avenue SE, Charleston, WV 25304" },
  { name: "Wisconsin", slug: "wisconsin", bar: "Wisconsin Office of Lawyer Regulation", barUrl: "https://www.wicourts.gov/courts/offices/olr.htm", barAddr: "110 E. Main Street, Suite 315, Madison, WI 53703", jc: "Wisconsin Judicial Commission", jcAddr: "110 E. Main Street, Suite 315, Madison, WI 53703" },
  { name: "Wyoming", slug: "wyoming", bar: "Wyoming State Bar", barUrl: "https://www.wyomingbar.org", barAddr: "4124 Laramie City Center, Cheyenne, WY 82001", jc: "Wyoming Commission on Judicial Conduct and Ethics", jcAddr: "2301 Central Avenue, Cheyenne, WY 82002" },
];
